### ISSUE TITLE
HashMap及ConcurrentHashMap的线程安全性验证

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#127]
这份ISSUE写在我对标题中这2个Collection源码分析之前

我希望多进行一些测试，就想到了如何验证HashMap的线程不安全性，在同样的环境下使用ConcurrentHashMap测试结果如何

最初我想到的是，构造2个线程，每个线程 map.put(1, map.get(1) + 1); 但测试发现2个Collection都表现了不安全性，对应例子1

然后网上看了篇文章 https://juejin.im/post/6844903951385493518 ，意识到了HashMap的线程不安全是发生在 出现hash碰撞时，对应例子2

下面还有一些问题值得思考
比如 除了hash碰撞外，HashMap还有什么线程不安全的表现点，扩容发生环状引用? => 已完成
比如 ConcurrentHashMap是如何保证hash碰撞时线程安全的

已总结于 深入理解JAVA并发与集合/HashMap面试题.md

**Comment by peteryuanpan** [comment]
### 例子1

```java
package hashmap;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

public class HashMapConcurrencyTest1 {

    //static Map<Integer, Integer> map = new HashMap<>();
    static Map<Integer, Integer> map = new ConcurrentHashMap<>();

    public static void main(String[] args) {
        map.put(1, 1);
        Thread a = new Thread(() -> {
            for (int i = 0; i < 10000; i ++) {
                map.put(1, map.get(1) + 1);
            }
        }, "threadA");
        Thread b = new Thread(a, "threadB");
        a.start();
        b.start();
        try {
            a.join();
            b.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println(map.get(1));
    }
}
```

HashMap输出结果
```
13515
```

ConcurrentHashMap输出结果
```
11876
```

解释：上面的线程不安全表现关键在于 Integer ，与HashMap本身无关

将例子改一下
```java
package hashmap;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

public class HashMapConcurrencyTest1 {

    //static Map<Integer, AtomicInteger> map = new HashMap<>();
    static Map<Integer, AtomicInteger> map = new ConcurrentHashMap<>();

    public static void main(String[] args) {
        AtomicInteger x = new AtomicInteger(0);
        map.put(1, x);
        Thread a = new Thread(() -> {
            for (int i = 0; i < 10000; i ++) {
                AtomicInteger t = map.get(1);
                t.getAndAdd(1);
                map.put(1, t);
            }
        }, "threadA");
        Thread b = new Thread(a, "threadB");
        a.start();
        b.start();
        try {
            a.join();
            b.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println(map.get(1));
    }
}
```

HashMap输出结果
```
20000
```

ConcurrentHashMap输出结果
```
20000
```

**Comment by peteryuanpan** [comment]
### 例子2

```java
package hashmap;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;

public class HashMapConcurrencyTest2 {

    //private static Map<String, String> map = new HashMap<>();
    private static Map<String, String> map = new ConcurrentHashMap<>();
    private static CountDownLatch countDownLatch;
    private static final int threadNum = 10;

    public static void main(String[] args) {
        Thread a = new Thread(() -> {
            try {
                for (int i = 0; i < 100; i ++) {
                    String s = Thread.currentThread().getName() + i;
                    map.put(s, s);
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                countDownLatch.countDown();
            }
        });

        countDownLatch = new CountDownLatch(threadNum);

        for (int i = 0; i < threadNum; i ++) {
            Thread t = new Thread(a, "Thread" + i + ": ");
            t.start();
        }

        try {
            countDownLatch.await();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        System.out.println(map.size());
    }
}
```

HashMap输出结果
```
989
```

ConcurrentHashMap输出结果
```
1000
```

解释：利用10个线程，一共往HashMap中打入1000个不同的String对象，HashMap表现出线程不安全了，ConcurrentHashMap没有，原因与hash碰撞有关，如果不发生hash碰撞，是不会出现KeySet缺少数据的，2个线程在同一个数组index位置上，插入链表元素时，可能出现线程1执行 a -> b 后，让出时间片，线程2执行 a -> c，这样 b 节点就丢失了

**Comment by peteryuanpan** [comment]
### 例子3

```java
package hashmap;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

public class HashMapConcurrencyTest3 {

    private static Map<String, String> map = new HashMap<>();
    //private static Map<String, String> map = new ConcurrentHashMap<>();

    public static void main(String[] args) {
        Thread a = new Thread(() -> {
            for (int i = 0; i < 1000000; i ++) {
                map.put(String.valueOf(i), String.valueOf(i));
            }
        });

        Thread b = new Thread(() -> {
            Iterator i = map.keySet().iterator();
            while (i.hasNext()) {
                i.next();
            }
        });

        a.start();
        b.start();

        try {
            a.join();
            b.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        System.out.println(Thread.currentThread().getName() + " end");
    }
}
```

HashMap输出结果
```
Exception in thread "Thread-1" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at hashmap.HashMapConcurrencyTest3.lambda$main$1(HashMapConcurrencyTest3.java:23)
	at java.lang.Thread.run(Thread.java:748)
main end
```

ConcurrentHashMap输出结果
```
main end
```

见 深入理解JAVA并发与集合/HashMap面试题.md

**Comment by peteryuanpan** [comment]
### 例子4

```java
package hashmap;

import java.util.HashMap;
import java.util.Map;

public class HashMapLinkedLoopProblemTest {

    static final int N = 100000;
    static String[] str_arr = new String[N];
    static Map<String, String> map = new HashMap<>();

    static {
        for (int i = 0; i < N; i ++)
            str_arr[i] = String.valueOf(i);
    }

    public static void main(String[] args) {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < N; i ++) {
                    System.out.println(Thread.currentThread().getName() + " " + i);
                    map.put(str_arr[i], str_arr[i]);
                }
            }
        });
        Thread a = new Thread(t, "ThreadA");
        Thread b = new Thread(t, "ThreadB");
        a.start();
        b.start();
        try {
            a.join();
            b.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println(Thread.currentThread().getName() + " end");
    }
}
```

输出结果（JDK7下运行，偶现，但复现率很高）
```
ThreadA 27034
ThreadA 27035
ThreadA 27036
...
ThreadB 21288
ThreadB 21289
ThreadB 21290
...
（不输出了，但程序在运行）
```

见 深入理解JAVA并发与集合/HashMap面试题.md
