### ISSUE TITLE
鲁班学院 第三期第二十八节 Spring中核心概念详解（看源码必备）

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#136]
简介
- 课程链接：https://ke.qq.com/user/index/index.html#/plan/cid=323635&tid=102917411&term_id=102917411
- 课程笔记：https://www.yuque.com/books/share/9f4576fb-9aa9-4965-abf3-b3a36433faa6/uqcp9i
- 上课老师：周瑜老师
- 上课时间：2020-10-11

Spring中核心概念详解（看源码必备）
1、BeanDefinition
2、AnnotatedBeanDefinitionReader
3、XmlBeanDefinitionReader
4、ClassPathBeanDefinitionScanner
5、BeanFactory
6、ApplicationContext
7、类型转化
8、BeanPostProcessor
9、BeanFactoryPostProcessor
10、FactoryBean

总结
- AnnotationConfigApplicationContext 是 Spring 最重要的一个容器之一，功能全面
Spring容器是用于存储Bean对象的，单例池 => BeanFactory => AnnotationConfigApplicationContext，都可以理解为Spring容器，而拥有不同的功能
- TODO：挑选课堂中的一个功能，分析源码，看底层是如何实现的

**Comment by peteryuanpan** [comment]
### 录播笔记 00:10:30 - 01:34:40

Spring中如何定义一个Bean
1.< bean />
2.@Bean
3.@Component(@Service, @Controller)
4.BeanDefinition

1-3是声明式的，4是编程式的，通过1-3方式，最终都会生成BeanDefinition，归于第4种。生成Bean对象前一定要生成BeanDefinition

直接定义BeanDefinition
```java
package com.luban.test;

import com.luban.entity.User;
import org.springframework.beans.factory.support.AbstractBeanDefinition;
import org.springframework.beans.factory.support.BeanDefinitionBuilder;
import org.springframework.beans.factory.support.DefaultListableBeanFactory;

public class Test3 {

	public static void main(String[] args) {
		AbstractBeanDefinition beanDefinition = BeanDefinitionBuilder.genericBeanDefinition().getBeanDefinition();
		beanDefinition.setBeanClass(User.class);
		DefaultListableBeanFactory defaultListableBeanFactory = new DefaultListableBeanFactory();
		defaultListableBeanFactory.registerBeanDefinition("user", beanDefinition);
		System.out.println(defaultListableBeanFactory.getBean("user"));
	}
}
```

还可以通过BeanDefinition设置一个Bean的其他属性
```java
beanDefinition.setScope("prototype"); // 设置作用域
beanDefinition.setInitMethodName("init"); // 设置初始化方法
beanDefinition.setAutowireMode(AutowireCapableBeanFactory.AUTOWIRE_BY_TYPE); // 设置自动装配模型
```

BeanDefinitionReader
- XmlBeanDefinitionReader，可以解析< bean />标签，转换为BeanDefinition
- AnnotatedBeanDefinitionReader，可以直接把某个类转换为BeanDefinition，并且会解析该类上的注解，能解析的注解是：@Conditional，@Scope、@Lazy、@Primary、@DependsOn、@Role、@Description

XmlBeanDefinitionReader
```java
package com.luban.test;

import org.springframework.beans.factory.xml.XmlBeanDefinitionReader;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Test4 {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext();
		XmlBeanDefinitionReader xmlBeanDefinitionReader = new XmlBeanDefinitionReader(annotationConfigApplicationContext); // 传入注册表
		int i = xmlBeanDefinitionReader.loadBeanDefinitions("spring.xml");
		System.out.println(i);
		annotationConfigApplicationContext.refresh(); // 需要刷新
		Object a = annotationConfigApplicationContext.getBean("userService");
		System.out.println(a);
		Object b = annotationConfigApplicationContext.getBean("orderService");
		System.out.println(b);
	}
}
```
spring.xml（在luban/src/main/resources下）
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xmlns:context="http://www.springframework.org/schema/context"
	   xmlns:aop="http://www.springframework.org/schema/aop"
	   xsi:schemaLocation="http://www.springframework.org/schema/beans
	   https://www.springframework.org/schema/beans/spring-beans.xsd http://www.springframework.org/schema/context https://www.springframework.org/schema/context/spring-context.xsd http://www.springframework.org/schema/aop https://www.springframework.org/schema/aop/spring-aop.xsd">

	<bean name="orderService" class="com.luban.service.OrderService"/>
	<bean name="userService" class="com.luban.service.UserService" autowire="byType"/>
</beans>
```
输出结果
```
2
com.luban.service.UserService@75a1cd57
com.luban.service.OrderService@3d012ddd
```

AnnotatedBeanDefinitionReader
```java
package com.luban.test;

import com.luban.service.OrderService;
import com.luban.service.UserService;
import org.springframework.context.annotation.AnnotatedBeanDefinitionReader;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Test5 {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext();
		AnnotatedBeanDefinitionReader annotatedBeanDefinitionReader = new AnnotatedBeanDefinitionReader(annotationConfigApplicationContext);// 传入注册表
		annotatedBeanDefinitionReader.register(UserService.class); // 注册一个Bean
		annotatedBeanDefinitionReader.register(OrderService.class); // 注册一个Bean
		annotationConfigApplicationContext.refresh(); // 需要刷新
		Object a = annotationConfigApplicationContext.getBean("userService");
		System.out.println(a);
		Object b = annotationConfigApplicationContext.getBean("orderService");
		System.out.println(b);
	}
}
```
输出结果
```
com.luban.service.UserService@5fcfe4b2
com.luban.service.OrderService@6bf2d08e
```

ClassPathBeanDefinitionScanner：这个并不是BeanDefinitionReader，但是它的作用和BeanDefinitionReader类似，它可以进行扫描，扫描某个包路径，对扫描到的类进行解析，比如，扫描到的类上如果存在@Component注解，那么就会把这个类解析为一个BeanDefinition

ClassPathBeanDefinitionScanner
```java
package com.luban.test;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ClassPathBeanDefinitionScanner;

public class Test6 {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext();
		ClassPathBeanDefinitionScanner classPathBeanDefinitionScanner = new ClassPathBeanDefinitionScanner(annotationConfigApplicationContext);
		classPathBeanDefinitionScanner.scan("com.luban");
		annotationConfigApplicationContext.refresh();
		Object a = annotationConfigApplicationContext.getBean("orderService");
		System.out.println(a);
	}
}
```
OrderService
```java
package com.luban.service;

import org.springframework.stereotype.Component;

@Component
public class OrderService {
}
```
输出结果
```
com.luban.service.OrderService@cac736f
```

DefaultListableBeanFactory
![image](https://user-images.githubusercontent.com/10209135/98323785-a50e7900-2025-11eb-83d8-f89bd06f0755.png)

类图中有好多接口和类：SingletonBeanRegistry（实现类 DefaultSingletonBeanRegistry，有单例池）、BeanDefinitionRegistry、BeanFactory、HierarchicalBeanFactory（有父工厂）、AliasRegistry（实现类 SimpleAliasRegistry）、ConfigurableBeanFactory、AutowireCapableBeanFactory（自动注入功能）、实现类AbstractAutowireCapableBeanFactory（整合多个功能）

这些接口的功能、含义，要慢慢理解，首先多应用，然后看实现类源码，最好能做到看到一个类implements了一个Interface，能马上知道它有哪些feature

抄一下羽雀笔记

DefaultListableBeanFactory实现了很多接口，拥有很多功能：
1. AliasRegistry：支持别名功能，一个名字可以对应多个别名
2. BeanDefinitionRegistry：可以注册、保存、移除、获取某个BeanDefinition
3. BeanFactory：Bean工厂，可以根据某个bean的名字、或类型、或别名获取某个Bean对象
4. SingletonBeanRegistry：可以直接注册、获取某个单例Bean
5. SimpleAliasRegistry：它是一个类，实现了AliasRegistry接口中所定义的功能，支持别名功能
6. ListableBeanFactory：在BeanFactory的基础上，增加了其他功能，可以获取所有BeanDefinition的beanNames，可以根据某个类型获取对应的beanNames，可以根据某个类型获取{类型：对应的Bean}的映射关系
7. HierarchicalBeanFactory：在BeanFactory的基础上，添加了获取父BeanFactory的功能
8. DefaultSingletonBeanRegistry：它是一个类，实现了SingletonBeanRegistry接口，拥有了直接注册、获取某个单例Bean的功能
9. ConfigurableBeanFactory：在HierarchicalBeanFactory和SingletonBeanRegistry的基础上，添加了设置父BeanFactory、类加载器（表示可以指定某个类加载器进行类的加载）、设置Spring EL表达式解析器（表示该BeanFactory可以解析EL表达式）、设置类型转化服务（表示该BeanFactory可以进行类型转化）、可以添加BeanPostProcessor（表示该BeanFactory支持Bean的后置处理器），可以合并BeanDefinition，可以销毁某个Bean等等功能
10. FactoryBeanRegistrySupport：支持了FactoryBean的功能
11. AutowireCapableBeanFactory：是直接继承了BeanFactory，在BeanFactory的基础上，支持在创建Bean的过程中能对Bean进行自动装配
12. AbstractBeanFactory：实现了ConfigurableBeanFactory接口，继承了FactoryBeanRegistrySupport，这个BeanFactory的功能已经很全面了，但是不能自动装配和获取beanNames
13. ConfigurableListableBeanFactory：继承了ListableBeanFactory、AutowireCapableBeanFactory、ConfigurableBeanFactory
14. AbstractAutowireCapableBeanFactory：继承了AbstractBeanFactory，实现了AutowireCapableBeanFactory，拥有了自动装配的功能
15. DefaultListableBeanFactory：继承了AbstractAutowireCapableBeanFactory，实现了ConfigurableListableBeanFactory接口和BeanDefinitionRegistry接口，所以DefaultListableBeanFactory的功能很强大

**Comment by peteryuanpan** [comment]
### 录播笔记 01:34:40 - 02:03:00

ApplicationContext是个接口，可以把它理解为一个特殊的BeanFactory
它有两个比较重要的实现类
- AnnotationConfigApplicationContext
- ClassPathXmlApplicationContext（相对于AnnotationConfigApplicationContext而言，功能没有AnnotationConfigApplicationContext强大，比如不能注册BeanDefinition）

ApplicationContext 有许多功能

1. HierarchicalBeanFactory：拥有获取父BeanFactory的功能
2. ListableBeanFactory：拥有获取beanNames的功能
3. ResourcePatternResolver：资源加载器，可以一次性获取多个资源（文件资源等等）
4. EnvironmentCapable：可以获取运行时环境（没有设置运行时环境功能）
5. ApplicationEventPublisher：拥有广播事件的功能（没有添加事件监听器的功能）
6. MessageSource：拥有国际化功能

```java
public interface ApplicationContext extends EnvironmentCapable, ListableBeanFactory, HierarchicalBeanFactory, MessageSource, ApplicationEventPublisher, ResourcePatternResolver {
```

AnnotationConfigApplicationContext延伸了许多功能

7. ConfigurableApplicationContext：继承了ApplicationContext接口，增加了，添加事件监听器、添加BeanFactoryPostProcessor、设置Environment，获取ConfigurableListableBeanFactory等功能
8. AbstractApplicationContext：实现了ConfigurableApplicationContext接口
9. GenericApplicationContext：继承了AbstractApplicationContext，实现了BeanDefinitionRegistry接口，拥有了所有ApplicationContext的功能，并且可以注册BeanDefinition，注意这个类中有一个属性(DefaultListableBeanFactory beanFactory)
10. AnnotationConfigRegistry：可以单独注册某个为类为BeanDefinition（可以处理该类上的@Configuration注解，已经可以处理@Bean注解），同时可以扫描
11. AnnotationConfigApplicationContext：继承了GenericApplicationContext，实现了AnnotationConfigRegistry接口，拥有了以上所有的功能

AnnotationConfigApplicationContext 类图

![image](https://user-images.githubusercontent.com/10209135/98338276-e8c4ab00-2044-11eb-9c66-e8bf7165b42c.png)

EnvironmentCapable 功能是获取System环境量

```java
package com.luban.test;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.core.env.ConfigurableEnvironment;

public class Test7 {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext();
		ConfigurableEnvironment environment = annotationConfigApplicationContext.getEnvironment();
		System.out.println(environment.getSystemEnvironment());
		System.out.println(environment.getSystemProperties());
	}
}
```

MessageSource 功能是国际化（支持不同自然语言）

resources/messages.properties
```
test=hello1
```

resources/messages_en_CN.properties
```
test=helloencn
```

AppConfig
```java
@ComponentScan("com.luban")
public class AppConfig {

	@Bean
	public MessageSource messageSource() {
		ResourceBundleMessageSource resourceBundleMessageSource = new ResourceBundleMessageSource();
		resourceBundleMessageSource.setBasename("messages");
		return resourceBundleMessageSource;
	}
```

MessageSource
```java
package com.luban.test;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import java.util.Locale;

public class Test8 {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext(AppConfig.class);
		System.out.println(annotationConfigApplicationContext.getMessage("test", null, new Locale("en_CN")));
	}
}
```

输出结果
```
helloencn
```

ApplicationEventPublisher 功能是时间发布监听器

AppConfig
```java
@ComponentScan("com.luban")
public class AppConfig {

	@Bean
	public ApplicationListener applicationListener() {
		return new ApplicationListener() {
			@Override
			public void onApplicationEvent(ApplicationEvent event) {
				System.out.println("接收到了一个事件");
			}
		};
	}
```

ApplicationEventPublisher
```java
package com.luban.test;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Test9 {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext(AppConfig.class);
		annotationConfigApplicationContext.publishEvent(new Object());
	}
}
```

输出结果
```
接收到了一个事件
接收到了一个事件
```

AnnotationConfigApplicationContext还支持加载一个资源（比如获取某个文件内容）

```java
package com.luban.test;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.core.io.Resource;

import java.io.IOException;

public class Test10 {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext();
		Resource resource = annotationConfigApplicationContext.getResource("spring.xml");
		try {
			System.out.println(resource.contentLength());
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
```

输出结果
```
873
```

AnnotationConfigApplicationContext 源码

```java
public class AnnotationConfigApplicationContext extends GenericApplicationContext implements AnnotationConfigRegistry {

	private final AnnotatedBeanDefinitionReader reader;

	private final ClassPathBeanDefinitionScanner scanner;
```

AnnotationConfigRegistry 源码

```java
public interface AnnotationConfigRegistry {

	/**
	 * Register one or more component classes to be processed.
	 * <p>Calls to {@code register} are idempotent; adding the same
	 * component class more than once has no additional effect.
	 * @param componentClasses one or more component classes,
	 * e.g. {@link Configuration @Configuration} classes
	 */
	void register(Class<?>... componentClasses);//  AnnotatedBeanDefinitionReader

	/**
	 * Perform a scan within the specified base packages.
	 * @param basePackages the packages to scan for component classes
	 */
	void scan(String... basePackages);  // ClassPathBeanDefinitionScanner

}
```

AnnotationConfigApplicationContext 中，AnnotatedBeanDefinitionReader reader 是用于实现 AnnotationConfigRegistry  的 register 功能的，ClassPathBeanDefinitionScanner scanner 是用于实现 ClassPathBeanDefinitionScanner 的 scan 功能的

ConfigurableApplicationContext也是一个接口，继承了 ApplicationContext，它添加了一些add、set方法，还有refresh方法

```java
public interface ConfigurableApplicationContext extends ApplicationContext, Lifecycle, Closeable {
	void addApplicationListener(ApplicationListener<?> listener);
	void addProtocolResolver(ProtocolResolver resolver);
	void refresh() throws BeansException, IllegalStateException;
	void setEnvironment(ConfigurableEnvironment environment);
	void setParent(@Nullable ApplicationContext parent);
```

SpringBoot启动时，使用形如 SpringApplication.run(UploadingFilesApplication.class, args); 的语句，返回值就是一个 AnnotationConfigApplicationContext

**Comment by peteryuanpan** [comment]
### 录播笔记 02:03:00 - last

将一下类型转换

User
```java
package com.luban.entity;

public class User {

	String name;

	public String getName() {
		return name;
	}

	public User(String name) {
		this.name = name;
	}
}
```

UserService
```java
package com.luban.service;

import com.luban.entity.User;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Component
public class UserService {

	@Value("user")
	private User user;

	public void test111() {
		System.out.println(user.getName());
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}
```

Test11
```java
package com.luban.test;

import com.luban.service.UserService;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Test11 {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext(AppConfig.class);
		UserService userService = annotationConfigApplicationContext.getBean("userService", UserService.class);
		userService.test111();
	}
}
```

这样会报错
```
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userService': Unsatisfied dependency expressed through field 'user'; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert value of type 'java.lang.String' to required type 'com.luban.entity.User'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'com.luban.entity.User': no matching editors or conversion strategy found
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:731)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:120)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:464)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1508)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:621)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:528)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:341)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:243)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:339)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:916)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:574)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:107)
	at com.luban.test.Test11.main(Test11.java:16)
Caused by: org.springframework.beans.ConversionNotSupportedException: Failed to convert value of type 'java.lang.String' to required type 'com.luban.entity.User'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'com.luban.entity.User': no matching editors or conversion strategy found
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:76)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1293)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1254)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:728)
	... 14 more
Caused by: java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'com.luban.entity.User': no matching editors or conversion strategy found
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:262)
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
	... 17 more

Process finished with exit code 1
```

怎么解决呢
- PropertyEditor
- ConversionService
- TypeConverter

PropertyEditor 是JDK中提供的类型转化工具类

StringToUserPropertyEditor
```java
package com.luban.util;

import com.luban.entity.User;

import java.beans.PropertyEditor;
import java.beans.PropertyEditorSupport;

public class StringToUserPropertyEditor extends PropertyEditorSupport implements PropertyEditor {

	@Override
	public void setAsText(String text) throws IllegalArgumentException {
		if ("user".equals(text)) {
			User user = new User(text);
			this.setValue(user);
		}
	}
}
```

测试一下
```java
package com.luban.test;

import com.luban.entity.User;
import com.luban.util.StringToUserPropertyEditor;

public class Test11_TEMP {

	public static void main(String[] args) {
		StringToUserPropertyEditor propertyEditor = new StringToUserPropertyEditor();
		propertyEditor.setAsText("user");
		User value = (User) propertyEditor.getValue();
		System.out.println(value.getName());
	}
}
```

输出结果
```
user
```

上面的不难理解，那么怎么在Spring中使用呢？

AppConfig
```java
@ComponentScan("com.luban")
public class AppConfig {

	@Bean
	public CustomEditorConfigurer customEditorConfigurer() {
		CustomEditorConfigurer customEditorConfigurer = new CustomEditorConfigurer();
		Map<Class<?>, Class<? extends PropertyEditor>> propertyEditorMap = new HashMap<>();
		propertyEditorMap.put(User.class, StringToUserPropertyEditor.class);
		customEditorConfigurer.setCustomEditors(propertyEditorMap);
		return customEditorConfigurer;
	}
```

再执行 Test11，输出结果
```
user
```

相当于是创建一个Bean CustomEditorConfigurer，Spring启动后会扫描这个Bean，其中有一个逻辑是setCustomEditors，参数的类型是 Map < Class < ? >, Class < ? extends PropertyEditor > > ，表示哪个类对应哪个PropertyEditor，那么Spring在获取UserService这个Bean的时候（UserService有@Component注解，因此它是一个Bean），由于private User user; 这个字段加了@Value("user")，就会去解析它，解析的时候就会使用上 CustomEditors，User.class 对应的 PropertyEditor 是 StringToUserPropertyEditor.class，就会执行 public void setAsText(String text) 方法完成类型转换，在getBean时执行public Object getValue() 方法获取 Object

还有一种方法 ConversionService

StringToUserConverter 
```java
package com.luban.util;

import com.luban.entity.User;
import org.springframework.core.convert.TypeDescriptor;
import org.springframework.core.convert.converter.ConditionalGenericConverter;

import java.util.Collections;
import java.util.Set;

public class StringToUserConverter implements ConditionalGenericConverter {

	@Override
	public boolean matches(TypeDescriptor sourceType, TypeDescriptor targetType) {
		return sourceType.getType().equals(String.class) && targetType.getType().equals(User.class);
	}

	@Override
	public Set<ConvertiblePair> getConvertibleTypes() {
		return Collections.singleton(new ConvertiblePair(String.class, User.class));
	}

	@Override
	public Object convert(Object source, TypeDescriptor sourceType, TypeDescriptor targetType) {
		User user = new User((String)source);
		return user;
	}
}
```

Test12_TEMP 
```java
package com.luban.test;

import com.luban.entity.User;
import com.luban.util.StringToUserConverter;
import org.springframework.core.convert.support.DefaultConversionService;

public class Test12_TEMP {

	public static void main(String[] args) {
		DefaultConversionService conversionService = new DefaultConversionService();
		conversionService.addConverter(new StringToUserConverter());
		User value = conversionService.convert("1", User.class);
		System.out.println(value.getName());
	}
}
```

输出结果
```
1
```

在Spring中如何使用呢

AppConfig

```java
@ComponentScan("com.luban")
public class AppConfig {

	@Bean
	public ConversionServiceFactoryBean conversionService() {
		ConversionServiceFactoryBean conversionServiceFactoryBean = new ConversionServiceFactoryBean();
		conversionServiceFactoryBean.setConverters(Collections.singleton(new StringToUserConverter()));
		return conversionServiceFactoryBean;
	}
```

Test12 

```java
package com.luban.test;

import com.luban.service.UserService;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class Test12 {

	public static void main(String[] args) {
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext(AppConfig.class);
		UserService userService = annotationConfigApplicationContext.getBean("userService", UserService.class);
		System.out.println(userService.getUser().getName());
	}
}
```

输出结果
```
user
```

最后是 TypeConverter，它 整合了PropertyEditor和ConversionService的功能，是Spring内部用的

Test13 

```java
package com.luban.test;

import com.luban.entity.User;
import com.luban.util.StringToUserPropertyEditor;
import org.springframework.beans.SimpleTypeConverter;

public class Test13 {

	public static void main(String[] args) {
		SimpleTypeConverter typeConverter = new SimpleTypeConverter();
		typeConverter.registerCustomEditor(User.class, new StringToUserPropertyEditor());
		User value = typeConverter.convertIfNecessary("user", User.class);
		System.out.println(value.getName());
	}
}
```

输出结果
```
user
```
