### ISSUE TITLE
SpringIOC学习总结

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#148]
目标
- 通过阅读文章 + 视频理解
- 通过代码例子深入理解之
- 做笔记总结

总结
- IOC关键词：管理Bean对象，对象生命周期，工厂模式，依赖注入（Dependency Inject），XML注入，注解注入，反射实例化，作用域（Scope）
- 一句话小结：IOC（控制反转），是一种基于工厂模式的思想，将对象创建、后置处理、销毁等过程交于Spring IOC容器管理，业务代码中只需要设定好BeanDefinition即可，剩下的工作由Spring来做（相当于点菜时写好菜单，厨师来做菜），设定BeanDefinition有传统的xml方式 和 后来的注解方式。依赖注入是指创建Bean时把依赖的属性注入到对象中，是一种实现方式。IOC在Spring内部是基于反射实现的

**Comment by peteryuanpan** [comment]
探索的过程中发现的宝藏，这篇文章写的很好：[CSDN：关于Spring IOC (DI-依赖注入)你需要知道的一切](https://blog.csdn.net/javazejian/article/details/54561302)

代码存于：D:\workspace\SpringBoot-Labs\lab-00-peter-test\src\main\java\csdn\javazejian\article54561302\ioc，我就不贴在ISSUE里了

Spring IOC 也是一个java对象，在某些特定的时间被创建后，可以进行对其他对象的控制，包括初始化、创建、销毁等，Spring的IOC容器都会帮我们完成，而我们唯一要做的就是把需要创建的类和其他类依赖的类以配置文件的方式告诉IOC容器需要创建那些类和注入哪些类即可

可以把IoC模式看做是工厂模式的升华，可以把IoC看作是一个大工厂，只不过这个大工厂里要生成的对象都是在配置文件（XML）中给出定义的，然后利用Java的反射技术，根据XML中给出的类名生成相应的对象

关于依赖注入
- 依赖注入的方式：xml注入、注解Autowired注入
- xml注入的方式：setter方法，构造方法（有循环依赖的问题），实例工厂，静态工厂，自动注入（autowired="byType|byName|constructor"）
- 注解Autowired注入的方式：属性、setter方法、构造方法
- 还有一种properties文件方式来注入，@Value + @PropertySource

Bean的重写机制原则是当声明的bean的名称一样时，后者会覆盖前者

Bean的作用域（scope）包含singleton（单例）与prototype（原型），Spring中Bean对象默认是单例的，可以通过 @Scope("prototype") 设置为原型，单例的Bean对象会放入单例池，这里与设计模式中单例模式、原型模式对应

Bean的作用域（scope）还包含request、session，在spring2.5中专门针对Web应用程序引进了request和session这两种作用域。关于request作用域，对于每次HTTP请求到达应用程序，Spring容器会创建一个全新的Request作用域的Bean实例，且该Bean实例仅在当前HTTP request内有效，整个请求过程也只会使用相同的Bean实例，因此我们可以根据需要放心的更改所建实例的内部状态，而其他请求HTTP请求则创建新Bean的实例互不干扰，当处理请求结束，request作用域的Bean实例将被销毁。关于Session可能你也已猜到，每当创建一个新的HTTP Session时就会创建一个Session作用域的Bean，并该实例Bean伴随着会话的存在而存在

Bean可以设置延迟加载，Spring容器将会延迟Bean的创建直到真正需要时才创建，一些特定的Bean可能只是某些场合需要而没必要在Spring容器启动阶段就创建，这样的Bean可能是Mybatis的SessionFactory或者Hibernate SessionFactory等，延迟加载它们会让Spring容器启动更轻松些，从而也减少没必要的内存消耗

**Comment by peteryuanpan** [comment]
下面例子诠释了2种注入方式（注解注入、XML注入），二者是等价的

```java
package autowired;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class AutowiredExample1 {

    public static void main(String[] args) {
        ClassPathXmlApplicationContext classPathXmlApplicationContext = new ClassPathXmlApplicationContext("autowired/spring-multiautowiredbytype.xml");
        System.out.println(classPathXmlApplicationContext.getBean("bean2"));
        AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext(AutowiredExample1Config.class);
        System.out.println(annotationConfigApplicationContext.getBean("bean2"));
    }
}

@Configuration
class AutowiredExample1Config {
    @Bean
    public AutowiredExample1Bean1 bean1() {
        return new AutowiredExample1Bean1();
    }
    @Bean
    public AutowiredExample1Bean2 bean2() {
        return new AutowiredExample1Bean2();
    }
}


class AutowiredExample1Bean1 {
    @Autowired
    AutowiredExample1Bean2 bean2;
}

class AutowiredExample1Bean2 {
}
```

autowired/spring-multiautowiredbytype.xml

```xml
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
        ">
    <bean name="bean1" autowire="byType" class="autowired.AutowiredExample1Bean1"/>
    <bean name="bean2" class="autowired.AutowiredExample1Bean2"/>
</beans>
```

输出结果
```
autowired.AutowiredExample1Bean2@3fee9989
autowired.AutowiredExample1Bean2@10db82ae
```

**Comment by peteryuanpan** [comment]
下面例子诠释了properties文件方式注入，@value + @PropertySource

```java
package autowired;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.stereotype.Component;

public class ConfigurationValueExample1 {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext(ConfigurationValueExample1Config.class);
        System.out.println(annotationConfigApplicationContext.getBean("configurationValueExample1Data", ConfigurationValueExample1Data.class));
    }
}

@PropertySource({"classpath:autowired/ConfigurationValueExample1.properties"})
@Configuration
class ConfigurationValueExample1Config {
    @Bean
    public ConfigurationValueExample1Data configurationValueExample1Data() {
        return new ConfigurationValueExample1Data();
    }
}

@Component
class ConfigurationValueExample1Data {
    @Value("${jdbc.url}")
    String value;
    @Value("${username}")
    String username;
    @Value("${password}")
    String password;

    @Override
    public String toString() {
        return "ConfigurationValueExample1Data{" +
            "value='" + value + '\'' +
            ", username='" + username + '\'' +
            ", password='" + password + '\'' +
            '}';
    }
}
```

autowired/ConfigurationValueExample1.properties
```properties
jdbc.url=mysql://xxx
username=aaa
password=bbb
```

输出结果
```
ConfigurationValueExample1Data{value='mysql://xxx', username='Admin', password='bbb'}
```

**Comment by peteryuanpan** [comment]
下面例子诠释了单例与原型Bean，实现方式是Configuration + Bean

```java
package scope;

import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Scope;

public class SingletonPrototypeExample1 {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext(SingletonPrototypeExample1Config.class);
        System.out.println(annotationConfigApplicationContext.getBean("bean1"));
        System.out.println(annotationConfigApplicationContext.getBean("bean1"));
        System.out.println(annotationConfigApplicationContext.getBean("bean2"));
        System.out.println(annotationConfigApplicationContext.getBean("bean2"));
        System.out.println(annotationConfigApplicationContext.getBean("bean1", SingletonPrototypeExample1Bean1.class).bean2);
        System.out.println(annotationConfigApplicationContext.getBean("bean1", SingletonPrototypeExample1Bean1.class).bean2);
        System.out.println(annotationConfigApplicationContext.getBean("bean2", SingletonPrototypeExample1Bean2.class).bean1);
        System.out.println(annotationConfigApplicationContext.getBean("bean2", SingletonPrototypeExample1Bean2.class).bean1);
        System.out.println(annotationConfigApplicationContext.getBean("bean3", SingletonPrototypeExample1Bean3.class).getBean2());
        System.out.println(annotationConfigApplicationContext.getBean("bean3", SingletonPrototypeExample1Bean3.class).getBean2());
    }
}

@Configuration
class SingletonPrototypeExample1Config {
    @Bean
    public SingletonPrototypeExample1Bean1 bean1() {
        return new SingletonPrototypeExample1Bean1();
    }

    @Scope("prototype")
    @Bean
    public SingletonPrototypeExample1Bean2 bean2() {
        return new SingletonPrototypeExample1Bean2();
    }

    @Bean
    public SingletonPrototypeExample1Bean3 bean3() {
        return new SingletonPrototypeExample1Bean3();
    }
}

class SingletonPrototypeExample1Bean1 {
    @Autowired
    SingletonPrototypeExample1Bean2 bean2;
}

class SingletonPrototypeExample1Bean2 {
    @Autowired
    SingletonPrototypeExample1Bean1 bean1;
}

class SingletonPrototypeExample1Bean3 implements ApplicationContextAware {

    SingletonPrototypeExample1Bean2 bean2;

    ApplicationContext applicationContext;

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }

    SingletonPrototypeExample1Bean2 getBean2() {
        return applicationContext.getBean("bean2", SingletonPrototypeExample1Bean2.class);
    }
}
```

输出结果
```
scope.SingletonPrototypeExample1Bean1@1a38c59b
scope.SingletonPrototypeExample1Bean1@1a38c59b
scope.SingletonPrototypeExample1Bean2@7f77e91b
scope.SingletonPrototypeExample1Bean2@44a664f2
scope.SingletonPrototypeExample1Bean2@7f9fcf7f
scope.SingletonPrototypeExample1Bean2@7f9fcf7f
scope.SingletonPrototypeExample1Bean1@1a38c59b
scope.SingletonPrototypeExample1Bean1@1a38c59b
scope.SingletonPrototypeExample1Bean2@2357d90a
scope.SingletonPrototypeExample1Bean2@6328d34a
```

解释
- bean1、bean3是单例Bean（默认），bean2是原型Bean
- 整个进程中，单例Bean只会创建一个实例（对应单例模式），原型Bean是只每次都会创建一个新的实例（对应原型模式），因此1、2行内存地址一样，3、4行内存地址不一样
- 5、6行内存地址一样，是因为bean1是单例的，虽然bean2是原型的，但是bean1只会创建一次，所以bean2只会注入一次
- 7、8行内存地址一样，也是因为bean1是单例的，且与1-2行内存地址一样
- 9、10行内存地址不一样，是因为使用了 implements ApplicationContextAware 的实现方式，放弃了自动依赖注入

上述例子还有一种实现方式，是ComponentScan + Scope
```java
package scope;

import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.context.annotation.*;
import org.springframework.stereotype.Component;

public class SingletonPrototypeExample1 {

    public static void main(String[] args) {
        AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext(SingletonPrototypeExample1Config.class);
        System.out.println(annotationConfigApplicationContext.getBean("bean1"));
        System.out.println(annotationConfigApplicationContext.getBean("bean1"));
        System.out.println(annotationConfigApplicationContext.getBean("bean2"));
        System.out.println(annotationConfigApplicationContext.getBean("bean2"));
        System.out.println(annotationConfigApplicationContext.getBean("bean1", SingletonPrototypeExample1Bean1.class).bean2);
        System.out.println(annotationConfigApplicationContext.getBean("bean1", SingletonPrototypeExample1Bean1.class).bean2);
        System.out.println(annotationConfigApplicationContext.getBean("bean2", SingletonPrototypeExample1Bean2.class).bean1);
        System.out.println(annotationConfigApplicationContext.getBean("bean2", SingletonPrototypeExample1Bean2.class).bean1);
        System.out.println(annotationConfigApplicationContext.getBean("bean3", SingletonPrototypeExample1Bean3.class).getBean2());
        System.out.println(annotationConfigApplicationContext.getBean("bean3", SingletonPrototypeExample1Bean3.class).getBean2());
    }
}

@ComponentScan("scope")
class SingletonPrototypeExample1Config {
}

@Component("bean1")
class SingletonPrototypeExample1Bean1 {
    @Autowired
    SingletonPrototypeExample1Bean2 bean2;
}

@Scope("prototype")
@Component("bean2")
class SingletonPrototypeExample1Bean2 {
    @Autowired
    SingletonPrototypeExample1Bean1 bean1;
}

@Component("bean3")
class SingletonPrototypeExample1Bean3 implements ApplicationContextAware {

    SingletonPrototypeExample1Bean2 bean2;

    ApplicationContext applicationContext;

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.applicationContext = applicationContext;
    }

    SingletonPrototypeExample1Bean2 getBean2() {
        return applicationContext.getBean("bean2", SingletonPrototypeExample1Bean2.class);
    }
}
```

**Comment by peteryuanpan** [comment]
下面例子诠释了Scope4种用法的区别

```java
package scope;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
public class RequestSessionExample1 {

    public static void main(String[] args) {
        SpringApplication.run(RequestSessionExample1.class, args);
    }
}

@RestController
class RequestSessionExample1Controller {
    @Autowired
    SingletonBean singletonBean;
    @Autowired
    PrototypeBean prototypeBean;
    @Autowired
    RequestBean requestBean;
    @Autowired
    SessionBean sessionBean;
    
    @RequestMapping(value = "/test")
    public void test() {
        System.out.println("first  time singleton is :" + singletonBean);
        System.out.println("second time singleton is :" + singletonBean);
        System.out.println("first  time prototype is :" + prototypeBean);
        System.out.println("second time prototype is :" + prototypeBean);
        System.out.println("first  time requestBean is :" + requestBean);
        System.out.println("second time requestBean is :" + requestBean);
        System.out.println("first  time sessionBean is :" + sessionBean);
        System.out.println("second time sessionBean is :" + sessionBean);
        System.out.println("===========================================");
    }
}

@Component
@Scope(value = "singleton")
class SingletonBean {
}

@Component
@Scope(value = "prototype", proxyMode = ScopedProxyMode.TARGET_CLASS)
class PrototypeBean {
}

@Component
@Scope(value = "request", proxyMode = ScopedProxyMode.TARGET_CLASS)
class RequestBean {
}

@Component
@Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
class SessionBean {
}
```

解释：一共访问了三次 http://localhost:8080/test ，第一次和第二次用chrome浏览器，第三次用edge浏览器
可以看出
- SingletonBean6次都是相同的内存地址
- PrototypeBean6次都是不同的内存地址
- RequestBean每次相同http请求是相同的内存地址
- SessionBean每次相同session（同一浏览器）是相同的内存地址

值得说明的是，上面使用了 3次 proxyMode = ScopedProxyMode.TARGET_CLASS 是必须的，去掉Session的会报如下错

错误的含义很明显，RequestSessionExample1Controller 类也是一个Bean，默认是单例Bean，要给单例Bean注入 PrototypeBean、RequestBean、SessionBean（不同的场景下注入新的实例对象而不是唯一不变的实例对象），需要设置代理模式，否则原型Bean会不生效，或者报错

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionBean': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:368) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
...
```

如果是 xml 注入，可以类似下面这样（经过测试这种声明代理的方式不适合prototype作用域，该作用域生效的方式目前测试中只有基于注解方式和前面基于实现ApplicationContextAware接口两种方式）

```xml
<bean id="requestBean" scope="request" class="scope.RequestBean" >
    <!-- 声明aop代理 -->
    <aop:scoped-proxy />
</bean>

<bean id="sessionBean" scope="request" class="scope.SessionBean" >
    <!-- 声明aop代理 -->
    <aop:scoped-proxy />
</bean>
```

这里是就涉及到 AOP 了
