### ISSUE TITLE
单例模式与原型模式

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#150]
单例模式：类的实例只有一个，每次初始化后得到的都是同一个内存地址的实例
原型模式：类的实例有很多，每次初始化后得到的都是不同内存地址的实例

单例模式有许多例子，比如JDK中的Unsafe类等
Spring中也有单例模式与原型模式...

单例模式有饿汉式与懒汉式，懒汉式有双重检查锁的写法，然而单例模式更推荐的方式是Enum枚举类

**Comment by peteryuanpan** [comment]
单例模式有两种基本写法，饿汉式 与 饱汉式

饿汉式
```java
package headfirst.P5_SingletonPattern;

public class HungryModel {

    private static HungryModel hungryModel = new HungryModel();

    private HungryModel() {}

    public static HungryModel getInstance() {
        return hungryModel;
    }
}
```

懒汉式
```java
package headfirst.P5_SingletonPattern;

public class UnhungryModel {

    private static volatile UnhungryModel unhungryModel;

    private UnhungryModel() {}

    public static UnhungryModel getInstance() {
        if (unhungryModel == null) {
            synchronized (UnhungryModel.class) {
                if (unhungryModel == null) {
                    unhungryModel = new UnhungryModel();
                }
            }
        }
        return unhungryModel;
    }
}
```

**Comment by peteryuanpan** [comment]
原型模式 与 Object#clone

```java
package headfirst.PX_PrototypePattern;

public class ObjectClone {

    public static void main(String[] args) {
        ObjectCloneA a1 = new ObjectCloneA();
        try {
            ObjectCloneA a2 = (ObjectCloneA) a1.clone();
            System.out.println(a1);
            System.out.println(a2);
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
        }
    }
}

class ObjectCloneA implements Cloneable {

    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}
```

输出结果
```
headfirst.PX_PrototypePattern.ObjectCloneA@1b6d3586
headfirst.PX_PrototypePattern.ObjectCloneA@4554617c
```

必须 implements Clonable，否则会报错
```
java.lang.CloneNotSupportedException: headfirst.PX_PrototypePattern.ObjectCloneA
	at java.lang.Object.clone(Native Method)
	at headfirst.PX_PrototypePattern.ObjectCloneA.clone(ObjectClone.java:20)
	at headfirst.PX_PrototypePattern.ObjectClone.main(ObjectClone.java:8)
```

**Comment by peteryuanpan** [comment]
参考 
- [Java单例模式的7种写法中，为何用Enum枚举实现被认为是最好的方式？](https://cloud.tencent.com/developer/article/1497592)
- [你知道吗？枚举单例模式是世界上最好的单例模式！！！](https://blog.csdn.net/weixin_36586120/article/details/105522491)

单例模式中有许多种写法，其中懒汉式的双重检查锁已经属于比较高级的写法了，但它依然存在问题
一，可以通过反射的方式重新创建对象
二，序列化与反序列化后不是同一个对象
三，写法比较复杂，运行效率不高

有一种方式能保证单例的安全性，即枚举类Enum
一，通过反射无法重新创建对象，底层做了屏蔽
```
private com.fsx.bean.EnumSingleton(java.lang.String,int)
Exception in thread "main" java.lang.IllegalArgumentException: Cannot reflectively create enum objects
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at com.fsx.maintest.Main.main(Main.java:22)
```
二，序列化与序列化后是同一个对象
```java
public class Main {

    public static void main(String[] args) {
        EnumSingleton s = EnumSingleton.INSTANCE;

        byte[] serialize = SerializationUtils.serialize(s);
        Object deserialize = SerializationUtils.deserialize(serialize);
        System.out.println(s == deserialize); //true
    }
}
```
三，写法也相对简单
