### ISSUE TITLE
鲁班学院 第三期第二十二节 Java并发ThreadPoolExecutor原理源码详解

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#161]
简介
- 课程链接：https://ke.qq.com/user/index/index.html#/plan/cid=323635&tid=102917411&term_id=102917411
- 课程笔记：https://www.yuque.com/books/share/9f4576fb-9aa9-4965-abf3-b3a36433faa6/bv45d9
- 上课老师：张金海
- 上课时间：2020-09-20

课程思考
- 线程池的好处和不足在哪儿？
- 线程池底层实现原理？
- 日常开发中如何用好线程池？

**Comment by peteryuanpan** [comment]
### 录播笔记 00:00:00 - 01:09:00

new Thread(Runnable x).start() 是 JAVA层面 启动线程的本质方法

要清楚 start() 和 run() 方法的区别

FutureTask是一个异步任务处理工具，配合 Callable，通过回调的方式（futureTask.get()）获取返回值

FutureTask是 实现了 RunnableFuture，RunnableFuture 继承 Runnable，因此启动线程方式本质不变

下面是代码例子

```java
package part1;

import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.FutureTask;

public class CallerTaskNewThread implements Callable<String> {

    @Override
    public String call() throws Exception {
        return "hello";
    }

    public static void main(String[] args) {
        FutureTask<String> futureTask = new FutureTask<>(new CallerTaskNewThread());
        new Thread(futureTask).start();
        try {
            String result = futureTask.get();
            System.out.println(result);
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }
    }
}
```

单任务线程池例子

```java
package threadpool;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ThreadPoolTest2 {

    static List<Integer> list = new ArrayList<>();
    static Random random = new Random();

    static void test1() {
        Long start = System.currentTimeMillis();
        for (int i = 0; i < 100000; i ++) {
            Thread a = new Thread(() -> {
                list.add(random.nextInt());
            });
            a.start();
            try {
                a.join();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        Long end = System.currentTimeMillis();
        System.out.println("cost: " + (end - start));
        System.out.println("size: " + list.size());
    }

    static void test2() {
        Long start = System.currentTimeMillis();
        ExecutorService executorService = Executors.newSingleThreadExecutor();
        for (int i = 0; i < 100000; i ++) {
            executorService.execute(() -> {
                list.add(random.nextInt());
            });
        }
        executorService.shutdown();
        Long end = System.currentTimeMillis();
        System.out.println("cost: " + (end - start));
        System.out.println("size: " + list.size());
    }

    public static void main(String[] args) {
        test1();
        //test2();
    }
}
```

输出结果（test1()）
```
cost: 15493
size: 100000
```

修改一下例子
```java
    public static void main(String[] args) {
        //test1();
        test2();
    }
```

输出结果（test2()）
```
cost: 58
size: 25040
```

解释：上面的例子，test1 和 test2 都是串行执行 1万个任务，但线程池做到了线程复用，例子1有1万次线程创建与销毁，而例子2没有，大大优化了运行效率


再来看一个例子，Executors中三种线程池创建方式

```java
package threadpool;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ThreadPoolTest3 {

    static final int N = 100;
    static CountDownLatch countDownLatch = new CountDownLatch(N);

    static ExecutorService executorService1 = Executors.newFixedThreadPool(10);
    static ExecutorService executorService2 = Executors.newCachedThreadPool();
    static ExecutorService executorService3 = Executors.newSingleThreadExecutor();

    public static void main(String[] args) {
        ExecutorService executorService = executorService1;
        Long start = System.currentTimeMillis();
        for (int i = 0; i < N; i ++) {
            executorService.execute(new MyTask(i));
        }
        try {
            countDownLatch.await();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Long end = System.currentTimeMillis();
        System.out.println("cost: " + (end - start));
        executorService.shutdown();
    }

    static class MyTask implements Runnable {

        int i = 0;

        public MyTask(int i) {
            this.i = i;
        }

        @Override
        public void run() {
            System.out.println(Thread.currentThread().getName() + "----" + i);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            countDownLatch.countDown();
        }
    }
}
```

输出结果（ExecutorService executorService = executorService1;）
```
cost: 10008
```

输出结果（ExecutorService executorService = executorService2;）
```
cost: 1013
```

输出结果（ExecutorService executorService = executorService3;）
```
cost: 100054
```

方式1，Executors.newFixedThreadPool(10);，核心线程数是10，最大线程数是10，最多有10个线程在执行

```java
public class Executors {
    public static ExecutorService newFixedThreadPool(int nThreads) {
        return new ThreadPoolExecutor(nThreads, nThreads,
                                      0L, TimeUnit.MILLISECONDS,
                                      new LinkedBlockingQueue<Runnable>());
    }
}
```

方式2，Executors.newCachedThreadPool();，核心线程数是0，最大线程数是Integer.MAX_VALUE

由于同步队列里面最多只有一个任务，一个任务被加入到同步队列后，其他任务无法被添加，只能到使用非核心线程运行（详细代码见更下方的execute方法）

keepAliveTime=60s表示只要当前线程在60s内空闲则回收

```java
public class Executors {
    public static ExecutorService newCachedThreadPool() {
        return new ThreadPoolExecutor(0, Integer.MAX_VALUE,
                                      60L, TimeUnit.SECONDS,
                                      new SynchronousQueue<Runnable>());
    }
}
```

![image](https://user-images.githubusercontent.com/10209135/99958544-86013c80-2dc4-11eb-97e8-ec1393f1cf1a.png)

方式3，Executors.newCachedThreadPool();，核心线程数是1，最大线程数是1，自始至终只有一个线程在执行

```java
public class Executors {
    public static ExecutorService newSingleThreadExecutor() {
        return new FinalizableDelegatedExecutorService
            (new ThreadPoolExecutor(1, 1,
                                    0L, TimeUnit.MILLISECONDS,
                                    new LinkedBlockingQueue<Runnable>()));
    }
}
```

execute方法中，先判断当前运行线程是否小于核心线程（workerCountOf(c) < corePoolSize），如果是，则使用核心线程运行（addWorker(command, true)），否则往队列中添加任务（isRunning(c) && workQueue.offer(command)），若添加成功，会使用非核心线程运行（addWorker(null, false)），若添加失败，也使用非核心线程运行（addWorker(command, false)），但注意第一个参数不一样

```java
public class ThreadPoolExecutor extends AbstractExecutorService {
    public void execute(Runnable command) {
        if (command == null)
            throw new NullPointerException();
        /*
         * Proceed in 3 steps:
         *
         * 1. If fewer than corePoolSize threads are running, try to
         * start a new thread with the given command as its first
         * task.  The call to addWorker atomically checks runState and
         * workerCount, and so prevents false alarms that would add
         * threads when it shouldn't, by returning false.
         *
         * 2. If a task can be successfully queued, then we still need
         * to double-check whether we should have added a thread
         * (because existing ones died since last checking) or that
         * the pool shut down since entry into this method. So we
         * recheck state and if necessary roll back the enqueuing if
         * stopped, or start a new thread if there are none.
         *
         * 3. If we cannot queue task, then we try to add a new
         * thread.  If it fails, we know we are shut down or saturated
         * and so reject the task.
         */
        int c = ctl.get();
        if (workerCountOf(c) < corePoolSize) {
            if (addWorker(command, true))
                return;
            c = ctl.get();
        }
        if (isRunning(c) && workQueue.offer(command)) {
            int recheck = ctl.get();
            if (! isRunning(recheck) && remove(command))
                reject(command);
            else if (workerCountOf(recheck) == 0)
                addWorker(null, false);
        }
        else if (!addWorker(command, false))
            reject(command);
    }
}
```

**Comment by peteryuanpan** [comment]
### 录播笔记 01:17:00 - last

创建10万个线程，慢的原因是，频繁的进行线程的创建和销毁，频繁的进行用户态与内核态切换，非常耗CPU资源

Executors.newFixedThreadPool(10) 有线程复用吗？当然有，比如 10个线程，100个任务

Executors.newFixedThreadPool(10)，只提交10个或10个以下任务，有线程复用吗？没有

keepAliveTime 参数是针对非核心线程的

corePoolSize = 核心线程数
maximumPoolSize - corePoolSize = 非核心线程数

阿里巴巴不推荐使用 Executors 中三种方式来线程池创建
第一种方式 n n，没有非核心线程，可能会有大量任务一直堆积在 new LinkedBlockingQueue<Runnable>() 实例中，这个队列的 capacity 是 Integer.MAX_VALUE 的
第二方式 0 max，最大线程数太大了，如果任务很多且执行时间长的话，达不到线程复用效果，会造成大量的线程创建和销毁
第三种方式 1 1，明显不合适，只是一种特殊方式

推荐的方式是，使用 ThreadPoolExecutor 的构造函数来创建

通过 execute 方法，可以发现线程池中，是否会创建非核心线程，很取决于同步队列的 capacity，LinkedBlockingQueue 这样的同步队列，默认构造方法中，capacity 是 Integer.MAX_VALUE 的，那么任务也许会一直进入同步队列中（workQueue.offer(command)），但如果有一个 capacity 限制，比如 corePoolSize = 10，maximumPoolSize = 100，capacity = 50，那么当10个核心线程创满了，且 Queue 中装满50个任务后，会开启非核心线程执行，如果总线程数达到了 maximumPoolSize 上限，还需要添加任务的话，会执行拒绝策略（也称饱和策略）

RejectedExecutionHandler 拒绝策略的接口，默认是如下4个实现类，分别是
- AbortPolicy（抛出异常，默认的 defaultHandler）
- CallerRunsPolicy（使用调用者所在的线程来运行）
- DiscardOldestPolicy（调用poll丢弃一个任务，执行当前线程）
- DiscardPolicy（默默丢弃，不抛出异常）

![image](https://user-images.githubusercontent.com/10209135/99964360-1ee88580-2dce-11eb-9352-31b654b68d34.png)

关于拒绝策略，来看个例子

```java
package threadpool;

import java.util.concurrent.*;

public class ThreadPoolTest3 {

    static final int N = 100;
    static CountDownLatch countDownLatch = new CountDownLatch(N);

    static ExecutorService executorService4 = new ThreadPoolExecutor(5, 10, 0, TimeUnit.SECONDS, new LinkedBlockingQueue<>(10));

    public static void main(String[] args) {
        ExecutorService executorService = executorService4;
        Long start = System.currentTimeMillis();
        for (int i = 0; i < N; i ++) {
            executorService.execute(new MyTask(i));
        }
        try {
            countDownLatch.await();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Long end = System.currentTimeMillis();
        System.out.println("cost: " + (end - start));
        executorService.shutdown();
    }

    static class MyTask implements Runnable {

        int i = 0;

        public MyTask(int i) {
            this.i = i;
        }

        @Override
        public void run() {
            System.out.println(Thread.currentThread().getName() + "----" + i);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            countDownLatch.countDown();
        }
    }
}
```

输出结果
```
pool-4-thread-2----1
pool-4-thread-1----0
pool-4-thread-3----2
pool-4-thread-9----18
pool-4-thread-5----4
pool-4-thread-8----17
pool-4-thread-7----16
pool-4-thread-4----3
pool-4-thread-10----19
pool-4-thread-6----15
Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task threadpool.ThreadPoolTest3$MyTask@7ea987ac rejected from java.util.concurrent.ThreadPoolExecutor@12a3a380[Running, pool size = 10, active threads = 10, queued tasks = 10, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at threadpool.ThreadPoolTest3.main(ThreadPoolTest3.java:19)
pool-4-thread-3----5
pool-4-thread-2----7
pool-4-thread-1----6
pool-4-thread-9----8
pool-4-thread-5----9
pool-4-thread-4----11
pool-4-thread-8----10
pool-4-thread-10----12
pool-4-thread-7----13
pool-4-thread-6----14
```

解释：核心线程数是5，最大线程数是10，队列容量是10，那么当最大线程数达到20（index=19）后，由于任务中需要 sleep 1s，线程都还在运行，此时再提交任务则会执行拒绝策略，抛出异常

线程池中，提交任务和执行任务的顺序是不一样的

提交任务：核心线程 => 队列 => 非核心线程
执行任务：核心线程 => 非核心线程 => 队列

![image](https://user-images.githubusercontent.com/10209135/99966020-a931e900-2dd0-11eb-87ef-e2ec0b744bf1.png)

线程池如何调优？
看业务，如果是IO型的（比如操作数据库），xxx
如果是CPU型的（比如处理图片），根据CPU核数，xxx
要跑多少任务（比如100个任务）
