### ISSUE TITLE
SpringCloud学习总结

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#191]
主学习资料
- https://github.com/macrozheng/springcloud-learning
- https://github.com/macrozheng/mall-swarm
- https://www.tulingxueyuan.cn/video/XLSP487x0x487xXL100174x
- https://www.tulingxueyuan.cn/video/XLSP364x0x364xXL100164x

每学完一个阶段后，回来看看mall-swarm的这幅微服务架构图，会有不同的理解

![image](https://user-images.githubusercontent.com/10209135/104094336-5c946580-52cb-11eb-80c9-970989b61b85.png)

**Comment by peteryuanpan** [comment]
参考
- https://www.zhihu.com/question/325225518
- [大话SpringCloud---为什么需要Spring Cloud Alibaba?](https://blog.csdn.net/jokeronee/article/details/108144195)
- [spring cloud 和 dubbo 各自的优缺点是什么?](https://www.zhihu.com/question/45413135)

Spring Cloud 本身其实只是一套微服务规范，并不是一个拿来即可用的框架，Spring Cloud Netflix 和 Spring Cloud alibaba 等是为开发者提供了这套规范的具体实现

Spring Cloud 微服务规范一般有以下内容
- 服务治理： Spring Cloud Eureka
- 客户端负载均衡： Spring Cloud Ribbon
- 服务容错保护： Spring Cloud Hystrix
- 声明式服务调用： Spring Cloud Feign
- API网关服务：Spring Cloud Zuul
- 分布式配置中心： Spring Cloud Config
- 消息总线： Spring Cloud Bus
- 消息驱动的微服务： Spring Cloud Stream
- 分布式服务跟踪： Spring Cloud Sleuth

SpringCloud微服务具体实现功能一览

![image](https://user-images.githubusercontent.com/10209135/103278673-0b50c000-4a07-11eb-8812-a4e51a88d58e.png)

由于Spring Cloud Netflix  2018年12月12日进入维护模式（Maintenance Mode），所以不太适合长期再使用。故选择Spring Cloud alibaba的技术方案

Spring Cloud Alibaba 包含组件

![image](https://user-images.githubusercontent.com/10209135/103278858-71d5de00-4a07-11eb-92de-39bbdb6759a7.png)

**Comment by peteryuanpan** [comment]
Spring Cloud Netflix Eureka

参考
- [Spring Cloud Eureka：服务注册与发现](https://juejin.cn/post/6844903940312530957)
- [Eureka 2.X 宣布停更，Spring Cloud 何去何从？](https://juejin.cn/post/6844904002467921934)

Eureka 2.X 已经停止维护了，替代方案之一是 Spring Cloud Alibaba Nacos

参考文档运行成功

![image](https://user-images.githubusercontent.com/10209135/104081702-59698d00-526b-11eb-84ec-a8b25c68578b.png)

**Comment by peteryuanpan** [comment]
Spring Cloud Alibaba Nacos

参考
- [Spring Cloud Alibaba：Nacos 作为注册中心和配置中心使用](https://juejin.cn/post/6844903993873793032)
- [mall-swarm在Windows环境下的部署](http://www.macrozheng.com/#/deploy/mall_swarm_deploy_windows)
- [Nacos 启动失败](https://www.cnblogs.com/rookiemzl/p/13814919.html)

到 https://github.com/alibaba/nacos/releases 中下载好 .zip 包后，windows10上打开失败，报错如下
```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authFilterRegistration' defined in class path resource [com/alibaba/nacos/core/auth/AuthConfig.class]: Bean instantiation via factory method failed
...
```

解决办法：修改文件 nacos/bin/startup.cmd，将 set MODE="cluster" 改为 set MODE="standalone"

访问 http://localhost:8848/nacos/ ，账号密码都是 nacos

![image](https://user-images.githubusercontent.com/10209135/103277562-4ef5fa80-4a04-11eb-8b41-cc2d0be2238f.png)

**Comment by peteryuanpan** [comment]
来自 [图灵学院-4.微服务介绍及Eureka服务注册与发现详解-司马](https://www.tulingxueyuan.cn/video/XLSP484x0x484xXL100174x)

SpringCloud中文社区：http://springcloud.cn/

SpringCloud架构图
![image](https://user-images.githubusercontent.com/10209135/104084980-043b7480-5287-11eb-9660-3a9360f3ebf5.png)

手写一个Eureka需要什么？
1）服务注册接口
2）服务发现接口
3）服务续约接口（续约=心跳）
4）服务注销接口
5）客户端缓存服务列表
6）客户端同步服务列表
等等

SpringCloud使用三板斧
1）加依赖
2）加注解
3）写配置文件

eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

电商系统微服务：订单、支付、库存、物流、积分

**Comment by peteryuanpan** [comment]
参考 [https://juejin.cn/post/6844903945026928654](https://juejin.cn/post/6844903945026928654)

一，疑问1

Hystrix的请求缓存功能，有疑问

在缓存使用过程中，我们需要在每次使用缓存的请求前后对HystrixRequestContext进行初始化和关闭，否则会出现如下异常：

```
java.lang.IllegalStateException: Request caching is not available. Maybe you need to initialize the HystrixRequestContext?
	at com.netflix.hystrix.HystrixRequestCache.get(HystrixRequestCache.java:104) ~[hystrix-core-1.5.18.jar:1.5.18]
	at com.netflix.hystrix.AbstractCommand$7.call(AbstractCommand.java:478) ~[hystrix-core-1.5.18.jar:1.5.18]
	at com.netflix.hystrix.AbstractCommand$7.call(AbstractCommand.java:454) ~[hystrix-core-1.5.18.jar:1.5.18]
```

这里我们通过使用过滤器，在每个请求前后初始化和关闭HystrixRequestContext来解决该问题

```java
/**
 * Created by macro on 2019/9/4.
 */
@Component
@WebFilter(urlPatterns = "/*",asyncSupported = true)
public class HystrixRequestContextFilter implements Filter {
    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {
        HystrixRequestContext context = HystrixRequestContext.initializeContext();
        try {
            filterChain.doFilter(servletRequest, servletResponse);
        } finally {
            context.close();
        }
    }
}
```

是的，没错，我把 implements Filter 去掉，就能复现出这个错误

但是，测试时也发现了，两次请求是不会共享缓存的，即每次新增请求就是一个新缓存，这是否与【每个请求前后初始化和关闭HystrixRequestContext】有关系呢？如果有关系，有没有办法让两次请求共享一个缓存呢？抑或，Hystrix的缓存就不是用于让两个请求共享一个缓存的？

仔细想了下，刚才理解的可能不太到位

下面是testCache的方法，加缓存的目的其实是为了减少微服务之间的请求，完整请求链是，客户端 => hystrix-service => user-service，那么 客户端 => hystrix-service 这一路请求是不需要用 hystrix 的缓存来做到两个请求共享一个缓存的，而 hystrix-service => user-service 已经可以做到了

```java
@RestController
@RequestMapping("/user")
public class UserHystrixController {

    @GetMapping("/testCache/{id}")
    public CommonResult testCache(@PathVariable Long id) {
        userService.getUserCache(id);
        userService.getUserCache(id);
        userService.getUserCache(id);
        return new CommonResult("操作成功", 200);
    }
}
```

二，疑问2

下面是合并请求功能，看起来是一个很不错的功能，但如何才能让getUserFuture(Long id)方法中的invoke方法被执行呢？

```java
@RestController
@RequestMapping("/user")
public class UserHystrixController {

    @GetMapping("/testCollapser")
    public CommonResult testCollapser() throws ExecutionException, InterruptedException {
        Future<User> future1 = userService.getUserFuture(1L);
        Future<User> future2 = userService.getUserFuture(2L);
        future1.get();
        future2.get();
        ThreadUtil.safeSleep(200);
        Future<User> future3 = userService.getUserFuture(3L);
        future3.get();
        return new CommonResult("操作成功", 200);
    }
}
```

```java
@Service
public class UserService {
    @HystrixCollapser(batchMethod = "getUserByIds",collapserProperties = {
            @HystrixProperty(name = "timerDelayInMilliseconds", value = "100")
    })
    public Future<User> getUserFuture(Long id) {
        return new AsyncResult<User>(){
            @Override
            public User invoke() {
                CommonResult commonResult = restTemplate.getForObject(userServiceUrl + "/user/{1}", CommonResult.class, id);
                Map data = (Map) commonResult.getData();
                User user = BeanUtil.mapToBean(data,User.class,true);
                LOGGER.info("getUserById username:{}", user.getUsername());
                return user;
            }
        };
    }

    @HystrixCommand
    public List<User> getUserByIds(List<Long> ids) {
        LOGGER.info("getUserByIds:{}", ids);
        CommonResult commonResult = restTemplate.getForObject(userServiceUrl + "/user/getUserByIds?ids={1}", CommonResult.class, CollUtil.join(ids,","));
        return (List<User>) commonResult.getData();
    }
}
```

**Comment by peteryuanpan** [comment]
参考 [Spring Cloud OpenFeign：基于Ribbon和Hystrix的声明式服务调用](https://juejin.cn/post/6844903959086235655)

Spring Cloud Netflix OpenFeign 是声明式服务调用工具，它整合了Ribbon和Hystrix，拥有负载均衡和服务容错功能

查看 spring-cloud-starter-openfeign-2.1.2.RELEASE.pom，可以看到有hystrix与ribbon的依赖

```xml
		<dependency>
			<groupId>io.github.openfeign</groupId>
			<artifactId>feign-hystrix</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
			<optional>true</optional>
		</dependency>
```

使用方式就几步，看起来很容易懂，如下

在启动类上添加@EnableFeignClients注解来启用Feign的客户端功能
```java
@EnableFeignClients
@EnableDiscoveryClient
@SpringBootApplication
public class FeignServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(FeignServiceApplication.class, args);
    }

}
```

添加UserService接口完成对user-service服务的接口绑定

```java
@FeignClient(value = "user-service")
public interface UserService {
    @PostMapping("/user/create")
    CommonResult create(@RequestBody User user);

    @GetMapping("/user/{id}")
    CommonResult<User> getUser(@PathVariable Long id);

    @GetMapping("/user/getByUsername")
    CommonResult<User> getByUsername(@RequestParam String username);

    @PostMapping("/user/update")
    CommonResult update(@RequestBody User user);

    @PostMapping("/user/delete/{id}")
    CommonResult delete(@PathVariable Long id);
}
```

添加UserFeignController调用UserService实现服务调用

```java
/**
 * Created by macro on 2019/8/29.
 */
@RestController
@RequestMapping("/user")
public class UserFeignController {
    @Autowired
    private UserService userService;

    @GetMapping("/{id}")
    public CommonResult getUser(@PathVariable Long id) {
        return userService.getUser(id);
    }

    @GetMapping("/getByUsername")
    public CommonResult getByUsername(@RequestParam String username) {
        return userService.getByUsername(username);
    }

    @PostMapping("/create")
    public CommonResult create(@RequestBody User user) {
        return userService.create(user);
    }

    @PostMapping("/update")
    public CommonResult update(@RequestBody User user) {
        return userService.update(user);
    }

    @PostMapping("/delete/{id}")
    public CommonResult delete(@PathVariable Long id) {
        return userService.delete(id);
    }
}
```

添加服务降级实现类UserFallbackService

```java
/**
 * Created by macro on 2019/9/5.
 */
@Component
public class UserFallbackService implements UserService {
    @Override
    public CommonResult create(User user) {
        User defaultUser = new User(-1L, "defaultUser", "123456");
        return new CommonResult<>(defaultUser);
    }

    @Override
    public CommonResult<User> getUser(Long id) {
        User defaultUser = new User(-1L, "defaultUser", "123456");
        return new CommonResult<>(defaultUser);
    }

    @Override
    public CommonResult<User> getByUsername(String username) {
        User defaultUser = new User(-1L, "defaultUser", "123456");
        return new CommonResult<>(defaultUser);
    }

    @Override
    public CommonResult update(User user) {
        return new CommonResult("调用失败，服务被降级",500);
    }

    @Override
    public CommonResult delete(Long id) {
        return new CommonResult("调用失败，服务被降级",500);
    }
}
``

**Comment by peteryuanpan** [comment]
参考 [Spring Cloud Zuul：API网关服务](https://juejin.cn/post/6844903960696848397)

下图描述了一个HTTP请求到达API网关后，如何在各种不同类型的过滤器中流转的过程

![image](https://user-images.githubusercontent.com/10209135/104094665-3f609680-52cd-11eb-898c-a27462b88dcc.png)
