### ISSUE TITLE
图灵学院第四期分布式框架专题——RocketMQ整体理解与快速实战

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#208]
简介
- 上课链接：https://www.tulingxueyuan.cn/video/XLSP811x0x811xXL100184x
- 上课老师：楼兰老师
- 上课时间：2020-12-06

资料
- 分布式专题，16-RocketMQ整体理解与快速实战-楼兰
- VIP01-RocketMQ整体理解与快速实战(1).pdf
- RocketMQ集群搭建详解
- rocketMQ-demo
- rocketmq-externals-master

总结
- 首先，我们要对MQ的优缺点以及适用场景开始要有逐渐清晰的概念。成熟的MQ产品上手使用都很简单，所以，使用和面试的重点从来都不会是怎么编程，而是能结合项目场景完整落地，这才是考验程序员功力的地方。而这个功力的要点就在于对异步消息驱动场景的理解深度。这一部分的学习最好能够结合kafka、RabbitMQ和RocketMQ这几个产品一起进行横向对比。当然，没有基础的同学也不用着急，但是在以后的学习中要有这个意识
- https://github.com/peteryuanpan/notebook/issues/208#issuecomment-778620508 中有代码例子
（1）本地Producer同步发送消息于服务器MQ
（2）本地Producer异步发送消息于服务器MQ
- rocketmq-console例子：https://github.com/peteryuanpan/notebook/issues/208#issuecomment-778775739
- TODO：rocketmq中一个生产者通过一个队列能给多个消费者发消息吗？

**Comment by peteryuanpan** [comment]
MQ：异步、解耦、削峰

消息一致性问题，A给B、C发消息，B成功，C失败，怎么保证消息数据处理的一致性

Kafka吞吐量非常大，性能好，集群高可用，但会丢数据，功能单一，适合日志分析、大数据采集场景

RabbitMQ吞吐量比较低，消息积累会影响性能，erlang语言不好定制，适合小规模场景

RocketMQ高吞吐，高性能，高可用，功能全面，开源版不如云上版，普通版不如铂金版，客户端只支持JAVA（影响生态），几乎适用所有场景

RocketMQ官方地址：http://rocketmq.apache.org/

参考文档 http://rocketmq.apache.org/docs/quick-start/ 安装
```
unzip rocketmq-all-4.8.0-source-release.zip
cd rocketmq-all-4.8.0/
mvn -Prelease-all -DskipTests clean install -U
```

得到如下结果
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache RocketMQ 4.8.0 4.8.0:
[INFO]
[INFO] Apache RocketMQ 4.8.0 .............................. SUCCESS [  6.255 s]
[INFO] rocketmq-logging 4.8.0 ............................. SUCCESS [  6.250 s]
[INFO] rocketmq-remoting 4.8.0 ............................ SUCCESS [  4.641 s]
[INFO] rocketmq-common 4.8.0 .............................. SUCCESS [ 12.583 s]
[INFO] rocketmq-client 4.8.0 .............................. SUCCESS [ 17.892 s]
[INFO] rocketmq-store 4.8.0 ............................... SUCCESS [  8.960 s]
[INFO] rocketmq-srvutil 4.8.0 ............................. SUCCESS [  0.817 s]
[INFO] rocketmq-filter 4.8.0 .............................. SUCCESS [ 24.631 s]
[INFO] rocketmq-acl 4.8.0 ................................. SUCCESS [  8.206 s]
[INFO] rocketmq-broker 4.8.0 .............................. SUCCESS [  6.653 s]
[INFO] rocketmq-tools 4.8.0 ............................... SUCCESS [  3.781 s]
[INFO] rocketmq-namesrv 4.8.0 ............................. SUCCESS [  1.649 s]
[INFO] rocketmq-logappender 4.8.0 ......................... SUCCESS [  9.528 s]
[INFO] rocketmq-test 4.8.0 ................................ SUCCESS [  8.252 s]
[INFO] rocketmq-openmessaging 4.8.0 ....................... SUCCESS [  2.995 s]
[INFO] rocketmq-example 4.8.0 ............................. SUCCESS [  2.190 s]
[INFO] rocketmq-distribution 4.8.0 ........................ SUCCESS [03:50 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:56 min
[INFO] Finished at: 2021-02-12T11:26:18+08:00
[INFO] ------------------------------------------------------------------------
```

执行
```
cd distribution/target/rocketmq-4.8.0/rocketmq-4.8.0

➜  rocketmq-4.8.0 pwd
/home/ubuntu/rocketmq/rocketmq-all-4.8.0-source-release/distribution/target/rocketmq-4.8.0/rocketmq-4.8.0

nohup sh bin/mqnamesrv &
```

遇到了报错
```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000006ec800000, 2147483648, 0) failed; error='Cannot allocate memory' (errno=12)
```

参考 [在linux上部署rocketMQ](https://www.jianshu.com/p/9bfb2c71d021)

在 bin/runserver.sh 中加一行，扩大一下JVM内存
```
JAVA_OPT="${JAVA_OPT} -server -Xms128m -Xmx256m -Xmn256m -XX:PermSize=128m -XX:MaxPermSize=320m"
```

再执行，OK

```
rocketmq-4.8.0/hs_err_pid9894.log
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=320m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using the DefNew young collector with the CMS collector is deprecated and will likely be removed in a future release
OpenJDK 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: MaxNewSize (262144k) is equal to or greater than the entire heap (262144k).  A new max generation size of 262080k will be used.
The Name Server boot success. serializeType=JSON
```

查看LOG确认

```
tail -f ~/logs/rocketmqlogs/namesrv.log
2021-02-12 12:08:15 INFO main - tls.client.authServer = false
2021-02-12 12:08:15 INFO main - tls.client.trustCertPath = null
2021-02-12 12:08:15 INFO main - Using OpenSSL provider
2021-02-12 12:08:16 INFO main - SSLContext created for server
2021-02-12 12:08:16 INFO main - Try to start service thread:FileWatchService started:false lastThread:null
2021-02-12 12:08:16 INFO NettyEventExecutor - NettyEventExecutor service started
2021-02-12 12:08:16 INFO main - The Name Server boot success. serializeType=JSON
2021-02-12 12:08:16 INFO FileWatchService - FileWatchService service started
2021-02-12 12:09:16 INFO NSScheduledThread1 - --------------------------------------------------------
2021-02-12 12:09:16 INFO NSScheduledThread1 - configTable SIZE: 0
```

同样的，启动broker

```
vi bin/runbroker.sh
JAVA_OPT="${JAVA_OPT} -server -Xms256m -Xmx256m -Xmn128m"

nohup sh bin/mqbroker -n localhost:9876 autoCreateTopicEnable=true &

cat ~/logs/rocketmqlogs/broker.log |grep "The broker"
2021-02-12 12:20:24 INFO main - The broker[VM-4-10-ubuntu, 10.0.4.10:10911] boot success. serializeType=JSON and name server is localhost:9876
```

发送消息
sh bin/tools.sh org.apache.rocketmq.example.quickstart.Producer | tee -a producer-log.txt

```
SendResult [sendStatus=SEND_OK, msgId=7F00000141301540E19D3B56BFE803E6, offsetMsgId=0A00040A00002A9F0000000000062F7E, messageQueue=MessageQueue [topic=TopicTest, brokerName=VM-4-10-ubuntu, queueId=1], queueOffset=499]
SendResult [sendStatus=SEND_OK, msgId=7F00000141301540E19D3B56BFE903E7, offsetMsgId=0A00040A00002A9F0000000000063049, messageQueue=MessageQueue [topic=TopicTest, brokerName=VM-4-10-ubuntu, queueId=2], queueOffset=499]
12:32:20.987 [NettyClientSelector_1] INFO  RocketmqRemoting - closeChannel: close the connection to remote address[10.0.4.10:10911] result: true
12:32:20.995 [NettyClientSelector_1] INFO  RocketmqRemoting - closeChannel: close the connection to remote address[127.0.0.1:9876] result: true
12:32:20.996 [NettyClientSelector_1] INFO  RocketmqRemoting - closeChannel: close the connection to remote address[127.0.0.1:9876] result: true
```

接收消息
sh bin/tools.sh org.apache.rocketmq.example.quickstart.Consumer | tee -a consumer-log.txt

```
ConsumeMessageThread_19 Receive New Messages: [MessageExt [brokerName=VM-4-10-ubuntu, queueId=3, storeSize=203, queueOffset=498, sysFlag=0, bornTimestamp=1613104340960, bornHost=/10.0.4.10:41986, storeTimestamp=1613104340960, storeHost=/10.0.4.10:10911, msgId=0A00040A00002A9F0000000000062ABC, commitLogOffset=404156, bodyCRC=836462227, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='TopicTest', flag=0, properties={MIN_OFFSET=0, MAX_OFFSET=500, CONSUME_START_TIME=1613104383105, UNIQ_KEY=7F00000141301540E19D3B56BFE003E0, CLUSTER=DefaultCluster, WAIT=true, TAGS=TagA}, body=[72, 101, 108, 108, 111, 32, 82, 111, 99, 107, 101, 116, 77, 81, 32, 57, 57, 50], transactionId='null'}]]
ConsumeMessageThread_3 Receive New Messages: [MessageExt [brokerName=VM-4-10-ubuntu, queueId=3, storeSize=203, queueOffset=499, sysFlag=0, bornTimestamp=1613104340964, bornHost=/10.0.4.10:41986, storeTimestamp=1613104340965, storeHost=/10.0.4.10:10911, msgId=0A00040A00002A9F0000000000062DE8, commitLogOffset=404968, bodyCRC=917938826, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='TopicTest', flag=0, properties={MIN_OFFSET=0, MAX_OFFSET=500, CONSUME_START_TIME=1613104383106, UNIQ_KEY=7F00000141301540E19D3B56BFE403E4, CLUSTER=DefaultCluster, WAIT=true, TAGS=TagA}, body=[72, 101, 108, 108, 111, 32, 82, 111, 99, 107, 101, 116, 77, 81, 32, 57, 57, 54], transactionId='null'}]]
```

可以开两个窗口，先启动Consumer，会得到如下
```
12:38:05.265 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
Consumer Started.
```

再启动Producer，Producer在发送消息时，Consumer在接收消息

**Comment by peteryuanpan** [comment]
RocketMQ集群中有以下角色
- Producer：消息的生产者
- Consumer：消息的消费者
- Broker：暂存和传输消息，实际处理业务的核心组件
- NameServer：管理Broker，类似于Zookeeper，功能是服务注册中心，但很轻量
- Topic：区分消息的种类，一个生产者可以发送消息给一个或多个Topic；一个消费者可以订阅一个或多个Topic

![image](https://user-images.githubusercontent.com/10209135/107851301-e6dc6600-6e43-11eb-9263-f6a885413963.png)

rocketmq官方没有提供如rabbitmq一样图形化管理界面，但在社区（rokcetmq-externals）中有提供rocketmq-console

rocketmq官网的DEMO是4.3.0的：http://rocketmq.apache.org/docs/simple-example/ ，但是学习的版本是4.7.1的（RocketMQ在4.5版本之前都不支持master宕机后slave自动切换。在4.5版本后，增加了基于Dleger实现的主从切换），楼兰老师很贴心地在资料中提供了rocketMQ-demo，是他自己整理的DEMO！

视频到了 00:47:30，到了代码部分！

**来看一个例子，本地Producer同步发送消息到服务器MQ**

测试代码
```java
package org.apache.rocketmq.example.simple;

import org.apache.rocketmq.client.exception.MQClientException;
import org.apache.rocketmq.client.producer.DefaultMQProducer;
import org.apache.rocketmq.common.message.Message;
import org.apache.rocketmq.remoting.common.RemotingHelper;

// 简单样例：同步发送消息
public class Producer {

    public static void main(String[] args) throws MQClientException {

        DefaultMQProducer producer = new DefaultMQProducer("ProducerGroupName");
        producer.setNamesrvAddr("<serverip>:9876");
        producer.start();

        for (int i = 0; i < 2; i++) {
            try {
                {
                    Message msg = new Message("TopicTest",
                        "TagA",
                        "OrderID188",
                        "Hello world".getBytes(RemotingHelper.DEFAULT_CHARSET));
                    // 同步传递消息，消息会发给集群中的一个Broker节点。
                    //SendResult sendResult = producer.send(msg);
                    //System.out.printf("%s%n", sendResult);
                    producer.sendOneway(msg);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        producer.shutdown();
    }
}
```

代码中 serverip 替换为服务端真实的ip，但这一步依然遇到了很多问题，有些问题是很容易解决的，
比如端口9876、10911不通，需要防火墙中开放
比如server没有启动完全，需要 nohup sh bin/mqnamesrv、nohup sh bin/mqbroker -n localhost:9876 autoCreateTopicEnable=true 都启动起来

但即时这样，还是遇到了如下报错

```
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to 10.0.4.10:10911 failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeOneway(NettyRemotingClient.java:554)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:471)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:431)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:854)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:584)
	... 3 more
org.apache.rocketmq.client.exception.MQClientException: Send [1] times, still failed, cost [3001]ms, Topic: TopicTest, BrokersSent: [VM-4-10-ubuntu]
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:665)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendOneway(DefaultMQProducerImpl.java:975)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.sendOneway(DefaultMQProducer.java:398)
	at org.apache.rocketmq.example.simple.Producer.main(Producer.java:43)
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to 10.0.4.10:10911 failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeOneway(NettyRemotingClient.java:554)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:471)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:431)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:854)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:584)
	... 3 more
```

解决方案参考：https://www.cnblogs.com/2YSP/p/11616376.html

在 /home/ubuntu/rocketmq/rocketmq-all-4.8.0-source-release/distribution/target/rocketmq-4.8.0/rocketmq-4.8.0 路径下，修改 conf/broker.conf 文件，添加一行，其中serverip填真实的服务器ip
```
brokerIP1=<serverip>
```

这样测试DEMO既可正常运行了

测试代码中发送了2个消息给服务端的MQ，此时启动服务器上MQ的消费者，可以得到如下结果，也是收到了2条消息

```
➜  rocketmq-4.8.0 sh bin/tools.sh org.apache.rocketmq.example.quickstart.Consumer
20:19:05.716 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
Consumer Started.
ConsumeMessageThread_1 Receive New Messages: [MessageExt [brokerName=broker-a, queueId=1, storeSize=212, queueOffset=1005, sysFlag=0, bornTimestamp=1613305155339, bornHost=/59.108.72.114:57814, storeTimestamp=1613305155226, storeHost=/150.158.175.76:10911, msgId=969EAF4C00002A9F00000000000C738C, commitLogOffset=816012, bodyCRC=198614610, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='TopicTest', flag=0, properties={MIN_OFFSET=0, MAX_OFFSET=1006, KEYS=OrderID188, CONSUME_START_TIME=1613305155252, UNIQ_KEY=C0A80166302818B4AAC2474EEF0B0001, CLUSTER=DefaultCluster, WAIT=true, TAGS=TagA}, body=[72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100], transactionId='null'}]]
ConsumeMessageThread_2 Receive New Messages: [MessageExt [brokerName=broker-a, queueId=0, storeSize=212, queueOffset=1005, sysFlag=0, bornTimestamp=1613305155300, bornHost=/59.108.72.114:57814, storeTimestamp=1613305155225, storeHost=/150.158.175.76:10911, msgId=969EAF4C00002A9F00000000000C72B8, commitLogOffset=815800, bodyCRC=198614610, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='TopicTest', flag=0, properties={MIN_OFFSET=0, MAX_OFFSET=1006, KEYS=OrderID188, CONSUME_START_TIME=1613305155255, UNIQ_KEY=C0A80166302818B4AAC2474EEEE30000, CLUSTER=DefaultCluster, WAIT=true, TAGS=TagA}, body=[72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100], transactionId='null'}]]
```

也可以先启动服务器上MQ的消费者，再发送消息，这样地验证更明显

顺便提一下，在conf下有三个文件夹：2m-2s-async、2m-2s-sync、2m-noslave，它们分别对应三种模式：2主2从异步、2主2从同步、2主无从，每种模式下还有独立的配置文件，这些模式与集群搭建有关

如何搭建集群可以见文档 RocketMQ集群搭建详解.pdf，我目前先不部署测试了

```
➜  conf ls
2m-2s-async  2m-noslave   dledger             logback_namesrv.xml  plain_acl.yml
2m-2s-sync   broker.conf  logback_broker.xml  logback_tools.xml    tools.yml
➜  conf ls 2m-2s-async
broker-a.properties  broker-a-s.properties  broker-b.properties  broker-b-s.properties
```

**再来看一个例子：本地Producer异步发送消息到服务器MQ**

```java
package org.apache.rocketmq.example.simple;

import org.apache.rocketmq.client.exception.MQClientException;
import org.apache.rocketmq.client.producer.DefaultMQProducer;
import org.apache.rocketmq.client.producer.SendCallback;
import org.apache.rocketmq.client.producer.SendResult;
import org.apache.rocketmq.common.message.Message;
import org.apache.rocketmq.remoting.common.RemotingHelper;

import java.io.UnsupportedEncodingException;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

// 简单样例：异步发送消息
public class AsyncProducer {
    public static void main(
        String[] args) throws MQClientException, InterruptedException {

        DefaultMQProducer producer = new DefaultMQProducer("Jodie_Daily_test");
        producer.setNamesrvAddr("<serverip>:9876");
        producer.start();
        producer.setRetryTimesWhenSendAsyncFailed(0);

        int messageCount = 2;
        // 由于是异步发送，这里引入一个countDownLatch，保证所有Producer发送消息的回调方法都执行完了再停止Producer服务
        final CountDownLatch countDownLatch = new CountDownLatch(messageCount);
        for (int i = 0; i < messageCount; i++) {
            try {
                final int index = i;
                Message msg = new Message("TopicTest",
                    "TagA",
                    "OrderID188",
                    "Hello world".getBytes(RemotingHelper.DEFAULT_CHARSET));
                producer.send(msg, new SendCallback() {
                    @Override
                    public void onSuccess(SendResult sendResult) {
                        countDownLatch.countDown();
                        System.out.printf("%-10d OK %s %n", index, sendResult.getMsgId());
                    }

                    @Override
                    public void onException(Throwable e) {
                        countDownLatch.countDown();
                        System.out.printf("%-10d Exception %s %n", index, e);
                        e.printStackTrace();
                    }
                });
                System.out.println("消息发送完成");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        countDownLatch.await(5, TimeUnit.SECONDS);
        producer.shutdown();
    }
}
```

服务端先启动Consumer
```
➜  rocketmq-all-4.8.0-bin-release sh bin/tools.sh org.apache.rocketmq.example.quickstart.Consumer
22:17:25.937 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
Consumer Started.
```

再执行代码，本地得到结果
```
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.PlatformDependent0).
RocketMQLog:WARN Please initialize the logger system properly.
消息发送完成
消息发送完成
0          OK C0A80166351C18B4AAC247BB3EC10001 
1          OK C0A80166351C18B4AAC247BB3EC10000 
```

服务端得到结果
```
➜  rocketmq-all-4.8.0-bin-release sh bin/tools.sh org.apache.rocketmq.example.quickstart.Consumer
22:17:25.937 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
Consumer Started.
ConsumeMessageThread_1 Receive New Messages: [MessageExt [brokerName=broker-a, queueId=3, storeSize=212, queueOffset=1005, sysFlag=0, bornTimestamp=1613312253633, bornHost=/59.108.72.114:49949, storeTimestamp=1613312253528, storeHost=/150.158.175.76:10911, msgId=969EAF4C00002A9F00000000000C7460, commitLogOffset=816224, bodyCRC=198614610, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='TopicTest', flag=0, properties={MIN_OFFSET=0, MAX_OFFSET=1007, KEYS=OrderID188, CONSUME_START_TIME=1613312253578, UNIQ_KEY=C0A80166351C18B4AAC247BB3EC10001, CLUSTER=DefaultCluster, WAIT=true, TAGS=TagA}, body=[72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100], transactionId='null'}]]
ConsumeMessageThread_2 Receive New Messages: [MessageExt [brokerName=broker-a, queueId=3, storeSize=212, queueOffset=1006, sysFlag=0, bornTimestamp=1613312253633, bornHost=/59.108.72.114:49949, storeTimestamp=1613312253538, storeHost=/150.158.175.76:10911, msgId=969EAF4C00002A9F00000000000C7534, commitLogOffset=816436, bodyCRC=198614610, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='TopicTest', flag=0, properties={MIN_OFFSET=0, MAX_OFFSET=1007, KEYS=OrderID188, CONSUME_START_TIME=1613312253584, UNIQ_KEY=C0A80166351C18B4AAC247BB3EC10000, CLUSTER=DefaultCluster, WAIT=true, TAGS=TagA}, body=[72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100], transactionId='null'}]]
```

视频到了01:10:00，上半场结束！

**Comment by peteryuanpan** [comment]
如何部署rocketmq console

参考：https://blog.csdn.net/so_geili/article/details/90142461

先git clone代码
git clone  https://github.com.cnpmjs.org/apache/rocketmq-externals.git

修改配置文件
cd rocketmq-externals/rocketmq-console/
vim src/main/resources/application.properties 
```
server.contextPath=/rocketmq
server.port=8081
rocketmq.config.namesrvAddr=localhost:9876
```
我8080端口被Jenkins占用了，因此改为8081

pwd
/home/ubuntu/rocketmq/rocketmq-externals/rocketmq-console

maven打包
mvn clean package -Dmaven.test.skip=true
```
...
Downloaded from central: https://repo.maven.apache.org/maven2/org/vafer/jdependency/2.1.1/jdependency-2.1.1.jar (186 kB at 2.0 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar (305 kB at 3.1 kB/s)
[INFO] Replacing main artifact with repackaged archive
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23:26 min
[INFO] Finished at: 2021-02-14T21:31:56+08:00
[INFO] ------------------------------------------------------------------------
```

```
ls target
checkstyle-cachefile    classes            maven-shared-archive-resources  rocketmq-console-ng-2.0.0.jar.original
checkstyle-checker.xml  generated-sources  maven-status
checkstyle-result.xml   maven-archiver     rocketmq-console-ng-2.0.0.jar
```

启动服务
```
nohup java -jar target/rocketmq-console-ng-2.0.0.jar
nohup: ignoring input and appending output to 'nohup.out'
```
查看 nohup.out 可确认启动成功

nginx中加一个配置
```
        location /rocketmq/ {
                proxy_pass  http://127.0.0.1:8081/;
        }
```

访问 https://mysite.peterpy.cn/rocketmq/#/ （没加登陆界面）

![image](https://user-images.githubusercontent.com/10209135/107878569-885aca80-6ecb-11eb-90c0-e1efae9349fd.png)
