### ISSUE TITLE
JAVA中HashMap与Hashtable的区别

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#66]
# JAVA中HashMap与Hashtable的区别

### 相同点
- 都实现了Map接口
- 都是键值对形式，不能包含重复键，但可以包含重复值

### 异同点
- 【重点】HashMap 允许 null key 和 null value，Hashtable 不允许
- 【重点】HashMap 是线程不安全的，Hashtable 是线程安全的（许多方法用了synchronized）
- HashMap 继承 AbstractMap 类，Hashtable 继承 Dictionary 类
- HashMap 使用 Iterator 来遍历，Hashtable 使用 Iterator + Enumeration 来遍历
- HashMap 在对象hashCode基础上用扰动函数重新计算，HashTable 直接使用对象的 hashCode
- HashMap中hash数组的默认大小是16，且扩容后一定是2的指数，HashTable中的hash数组初始大小是11，扩容方式是 old*2+1

### 参考
- https://www.nowcoder.com/test/question/done?tid=36092716&qid=14454#summary
- https://www.jianshu.com/p/5c34133ed372
- https://blog.csdn.net/u010983881/article/details/49762595
- https://www.zhihu.com/question/20733617

**Comment by peteryuanpan** [comment]
### HashMap及Hashtable类及父类的申明
```java
public class HashMap<K,V> extends AbstractMap<K,V> implements Map<K,V>, Cloneable, Serializable{}

public abstract class AbstractMap<K,V> implements Map<K,V>{}

public class Hashtable<K,V> extends Dictionary<K,V> implements Map<K,V>, Cloneable, java.io.Serializable{}

public abstractclass Dictionary<K,V>{}
```

### 都实现了Map接口
显然

### HashMap 继承 AbstractMap 类，Hashtable 继承 Dictionary 类
显然

**Comment by peteryuanpan** [comment]
### HashMap 关于 put 源码（JDK1.8 ）
```java
    /**
     * Associates the specified value with the specified key in this map.
     * If the map previously contained a mapping for the key, the old
     * value is replaced.
     *
     * @param key key with which the specified value is to be associated
     * @param value value to be associated with the specified key
     * @return the previous value associated with <tt>key</tt>, or
     *         <tt>null</tt> if there was no mapping for <tt>key</tt>.
     *         (A <tt>null</tt> return can also indicate that the map
     *         previously associated <tt>null</tt> with <tt>key</tt>.)
     */
    public V put(K key, V value) {
        return putVal(hash(key), key, value, false, true);
    }

    /**
     * Implements Map.put and related methods
     *
     * @param hash hash for key
     * @param key the key
     * @param value the value to put
     * @param onlyIfAbsent if true, don't change existing value
     * @param evict if false, the table is in creation mode.
     * @return previous value, or null if none
     */
    final V putVal(int hash, K key, V value, boolean onlyIfAbsent,
                   boolean evict) {
        Node<K,V>[] tab; Node<K,V> p; int n, i;
        if ((tab = table) == null || (n = tab.length) == 0)
            n = (tab = resize()).length;
        if ((p = tab[i = (n - 1) & hash]) == null)
            tab[i] = newNode(hash, key, value, null);
        else {
            Node<K,V> e; K k;
            if (p.hash == hash &&
                ((k = p.key) == key || (key != null && key.equals(k))))
                e = p;
            else if (p instanceof TreeNode)
                e = ((TreeNode<K,V>)p).putTreeVal(this, tab, hash, key, value);
            else {
                for (int binCount = 0; ; ++binCount) {
                    if ((e = p.next) == null) {
                        p.next = newNode(hash, key, value, null);
                        if (binCount >= TREEIFY_THRESHOLD - 1) // -1 for 1st
                            treeifyBin(tab, hash);
                        break;
                    }
                    if (e.hash == hash &&
                        ((k = e.key) == key || (key != null && key.equals(k))))
                        break;
                    p = e;
                }
            }
            if (e != null) { // existing mapping for key
                V oldValue = e.value;
                if (!onlyIfAbsent || oldValue == null)
                    e.value = value;
                afterNodeAccess(e);
                return oldValue;
            }
        }
        ++modCount;
        if (++size > threshold)
            resize();
        afterNodeInsertion(evict);
        return null;
    }
```
### HashMap 关于 get 源码（JDK1.8）
```java
    /**
     * Returns the value to which the specified key is mapped,
     * or {@code null} if this map contains no mapping for the key.
     *
     * <p>More formally, if this map contains a mapping from a key
     * {@code k} to a value {@code v} such that {@code (key==null ? k==null :
     * key.equals(k))}, then this method returns {@code v}; otherwise
     * it returns {@code null}.  (There can be at most one such mapping.)
     *
     * <p>A return value of {@code null} does not <i>necessarily</i>
     * indicate that the map contains no mapping for the key; it's also
     * possible that the map explicitly maps the key to {@code null}.
     * The {@link #containsKey containsKey} operation may be used to
     * distinguish these two cases.
     *
     * @see #put(Object, Object)
     */
    public V get(Object key) {
        Node<K,V> e;
        return (e = getNode(hash(key), key)) == null ? null : e.value;
    }

    /**
     * Implements Map.get and related methods
     *
     * @param hash hash for key
     * @param key the key
     * @return the node, or null if none
     */
    final Node<K,V> getNode(int hash, Object key) {
        Node<K,V>[] tab; Node<K,V> first, e; int n; K k;
        if ((tab = table) != null && (n = tab.length) > 0 &&
            (first = tab[(n - 1) & hash]) != null) {
            if (first.hash == hash && // always check first node
                ((k = first.key) == key || (key != null && key.equals(k))))
                return first;
            if ((e = first.next) != null) {
                if (first instanceof TreeNode)
                    return ((TreeNode<K,V>)first).getTreeNode(hash, key);
                do {
                    if (e.hash == hash &&
                        ((k = e.key) == key || (key != null && key.equals(k))))
                        return e;
                } while ((e = e.next) != null);
            }
        }
        return null;
    }

    /**
     * Computes key.hashCode() and spreads (XORs) higher bits of hash
     * to lower.  Because the table uses power-of-two masking, sets of
     * hashes that vary only in bits above the current mask will
     * always collide. (Among known examples are sets of Float keys
     * holding consecutive whole numbers in small tables.)  So we
     * apply a transform that spreads the impact of higher bits
     * downward. There is a tradeoff between speed, utility, and
     * quality of bit-spreading. Because many common sets of hashes
     * are already reasonably distributed (so don't benefit from
     * spreading), and because we use trees to handle large sets of
     * collisions in bins, we just XOR some shifted bits in the
     * cheapest possible way to reduce systematic lossage, as well as
     * to incorporate impact of the highest bits that would otherwise
     * never be used in index calculations because of table bounds.
     */
    static final int hash(Object key) {
        int h;
        return (key == null) ? 0 : (h = key.hashCode()) ^ (h >>> 16);
    }
```

**Comment by peteryuanpan** [comment]
### Hashtable 关于 put 源码（JDK1.8 ）
```java
    /**
     * Maps the specified <code>key</code> to the specified
     * <code>value</code> in this hashtable. Neither the key nor the
     * value can be <code>null</code>. <p>
     *
     * The value can be retrieved by calling the <code>get</code> method
     * with a key that is equal to the original key.
     *
     * @param      key     the hashtable key
     * @param      value   the value
     * @return     the previous value of the specified key in this hashtable,
     *             or <code>null</code> if it did not have one
     * @exception  NullPointerException  if the key or value is
     *               <code>null</code>
     * @see     Object#equals(Object)
     * @see     #get(Object)
     */
    public synchronized V put(K key, V value) {
        // Make sure the value is not null
        if (value == null) {
            throw new NullPointerException();
        }

        // Makes sure the key is not already in the hashtable.
        Entry<?,?> tab[] = table;
        int hash = key.hashCode();
        int index = (hash & 0x7FFFFFFF) % tab.length;
        @SuppressWarnings("unchecked")
        Entry<K,V> entry = (Entry<K,V>)tab[index];
        for(; entry != null ; entry = entry.next) {
            if ((entry.hash == hash) && entry.key.equals(key)) {
                V old = entry.value;
                entry.value = value;
                return old;
            }
        }

        addEntry(hash, key, value, index);
        return null;
    }
```
### Hashtable 关于 get 源码（JDK1.8）
```java
    /**
     * Returns the value to which the specified key is mapped,
     * or {@code null} if this map contains no mapping for the key.
     *
     * <p>More formally, if this map contains a mapping from a key
     * {@code k} to a value {@code v} such that {@code (key.equals(k))},
     * then this method returns {@code v}; otherwise it returns
     * {@code null}.  (There can be at most one such mapping.)
     *
     * @param key the key whose associated value is to be returned
     * @return the value to which the specified key is mapped, or
     *         {@code null} if this map contains no mapping for the key
     * @throws NullPointerException if the specified key is null
     * @see     #put(Object, Object)
     */
    @SuppressWarnings("unchecked")
    public synchronized V get(Object key) {
        Entry<?,?> tab[] = table;
        int hash = key.hashCode();
        int index = (hash & 0x7FFFFFFF) % tab.length;
        for (Entry<?,?> e = tab[index] ; e != null ; e = e.next) {
            if ((e.hash == hash) && e.key.equals(key)) {
                return (V)e.value;
            }
        }
        return null;
    }
```

**Comment by peteryuanpan** [comment]
### 都是键值对形式，不能包含重复键，但可以包含重复值
从put源码可以看出来，HashMap和Hashtable都符合一个逻辑，当新的元素<key, value>进来后，计算hash值，若已存在一个元素hash和key与当前元素相同，则使用当前元素的value替换已存在的元素的value，因此不能包含重复键。显然可以包含重复值

对应代码块
HashMap
```java
            if (p.hash == hash &&
                ((k = p.key) == key || (key != null && key.equals(k))))
                e = p;
            else {
                for (int binCount = 0; ; ++binCount) {
                    if ((e = p.next) == null) {
                                 .......
                    }
                    if (e.hash == hash &&
                        ((k = e.key) == key || (key != null && key.equals(k))))
                        break;
                    p = e;
                }
            }
```
Hashtable
```java
        for(; entry != null ; entry = entry.next) {
            if ((entry.hash == hash) && entry.key.equals(key)) {
                V old = entry.value;
                entry.value = value;
                return old;
            }
        }
```

**Comment by peteryuanpan** [comment]
### HashMap 允许 null key 和 null value，Hashtable 不允许

进行一下测试就知道
code1
```java
package com.luban.ziya.peter;

import java.util.HashMap;
import java.util.Hashtable;

public class TEST1 {

    public static void main(String[] args) {
        HashMap<String, String> a = new HashMap<String, String>();
        a.put(null, "2");
        a.put("1", null);
        System.out.println(a.get(null));
        System.out.println(a.get("1"));

        Hashtable<String, String> b = new Hashtable<String, String>();
        try {
            b.put(null, "");
            System.out.println(b.get(null));
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            b.put("", null);
            System.out.println(b.get(""));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

输出结果为
```
2
null
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:465)
	at com.luban.ziya.peter.TEST1.main(TEST1.java:17)
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at com.luban.ziya.peter.TEST1.main(TEST1.java:23)
```

从HashMap源码中，看不出任何对null key以及null value的限制

从Hashtable源码中，可以看到

两处
- value == null，保证了value不为null
- int hash = key.hashCode();，保证了key不为null

```java
    public synchronized V put(K key, V value) {
        // Make sure the value is not null
        if (value == null) {
            throw new NullPointerException();
        }

        // Makes sure the key is not already in the hashtable.
        Entry<?,?> tab[] = table;
        int hash = key.hashCode();
...
    }
```

**Comment by peteryuanpan** [comment]
### HashMap 是线程不安全的，Hashtable 是线程安全的（许多方法用了synchronized）

来枚举一下方法的declaration

|方法|HashMap|Hashtable|
|--|--|--|
|put|public V put(K key, V value)<br>final V putVal(int hash, K key, V value, boolean onlyIfAbsent,boolean evict)|public synchronized V put(K key, V value)|
|get|public V get(Object key)<br>final Node<K,V> getNode(int hash, Object key)|public synchronized V get(Object key)|
|remove|public V remove(Object key)<br>public boolean remove(Object key, Object value)<br>final Node<K,V> removeNode(int hash, Object key, Object value,boolean matchValue, boolean movable)|public synchronized V remove(Object key)<br>public synchronized boolean remove(Object key, Object value)|
|replace|public V replace(K key, V value)<br>public boolean replace(K key, V oldValue, V newValue)<br>public void replaceAll(BiFunction<? super K, ? super V, ? extends V> function)|public synchronized V replace(K key, V value)<br>public synchronized boolean replace(K key, V oldValue, V newValue)<br>public synchronized void replaceAll(BiFunction<? super K, ? super V, ? extends V> function)|
|clear|public void clear()|public synchronized void clear()|
|containsKey|public boolean containsKey(Object key)<br>final Node<K,V> getNode(int hash, Object key)|public synchronized boolean containsKey(Object key)|
|containsValue|public boolean containsValue(Object value)|public boolean containsValue(Object value)<br>public synchronized boolean contains(Object value)|
|size|public int size()|public synchronized int size()|
|isEmpty|public boolean isEmpty()|public synchronized boolean isEmpty()|
|keys|public Set<K> keySet()|public synchronized Enumeration<K> keys()|
|values|public Collection<V> values()|public synchronized Enumeration<V> elements()|
|entrySet|public Set<Map.Entry<K,V>> entrySet()|public Set<Map.Entry<K,V>> entrySet()|
|hashCode||public synchronized int hashCode()|
|equals||public synchronized boolean equals(Object o)|
|toString||public synchronized String toString()|

可以看出除了entrySet方法外，Hashtable方法都加了synchronized修饰符，连hashCode、equals、toString这三个都加了

关于synchronized的理解可见：https://github.com/peteryuanpan/notebook/issues/68

**Comment by peteryuanpan** [comment]
### HashMap 使用 Iterator 来遍历，Hashtable 使用 Iterator + Enumeration 来遍历
TODO

**Comment by peteryuanpan** [comment]
### HashMap 在对象hashCode基础上用扰动函数重新计算，HashTable 直接使用对象的 hashCode
TODO

**Comment by peteryuanpan** [comment]
### HashMap中hash数组的默认大小是16，且扩容后一定是2的指数，HashTable中的hash数组初始大小是11，扩容方式是 old*2+1
TODO
