### ISSUE TITLE
JAVA中关于反射的理解

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#77]
参考
- [大白话说Java反射：入门、使用、原理](https://www.cnblogs.com/chanshuyi/p/head_first_of_reflection.html)
- [深入解析Java反射（1） - 基础](https://www.sczyh30.com/posts/Java/java-reflection-1/)
- [掘金：Java 反射由浅入深 | 进阶必备](https://juejin.im/post/6844904005294882830)
- [简书：Java反射到底慢在哪？](https://www.jianshu.com/p/4e2b49fa8ba1)
- [掘金：Java 反射真的很慢吗？](https://juejin.im/post/6844904098207105038#heading-0)
- [知乎：Java的反射调用性能很低吗?](https://zhuanlan.zhihu.com/p/55075493)

总结
- 反射很强大
- 反射不一定很慢，要具体场景测试

**Comment by peteryuanpan** [comment]
反射是比较神奇的，它能调用一个类的 private 字段 和 方法，相当于JAVA设计中留了一个“后门”给程序员使用

```java
package reflect;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class ReflectTest1 {

    public static void main(String[] args) {
        try {
            Class<?> aClass = Class.forName("reflect.ReflectTest11");
            System.out.println(aClass.getName());

            ReflectTest11 obj = (ReflectTest11) aClass.newInstance();
            System.out.println(obj);

            Field fielda = aClass.getDeclaredField("a");
            fielda.setAccessible(true);
            int vara = (int) fielda.get(obj);
            System.out.println(vara);

            Method func = aClass.getDeclaredMethod("func");
            func.setAccessible(true);
            func.invoke(obj);

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
    }
}

class ReflectTest11 {
    public ReflectTest11() {}
    private int a = 1;
    private void func() {
        System.out.println("func");
    }
}
```

输出结果
```
reflect.ReflectTest11
reflect.ReflectTest11@1b6d3586
1
func
```

**Comment by peteryuanpan** [comment]
反射new一个单例模式中的实例

单例模式中，类的构造方法是private修饰的

```java
package reflect;

public class ReflectTest2 {

    public static void main(String[] args) {
        try {
            Class<?> aClass = Class.forName("reflect.ReflectTest21");
            System.out.println(aClass.getName());

            ReflectTest21 obj = (ReflectTest21) aClass.newInstance();
            System.out.println(obj);

        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
}

class ReflectTest21 {
    private static ReflectTest21 reflectTest21 = new ReflectTest21();
    private ReflectTest21() {}
    public static ReflectTest21 getInstance() {
        return reflectTest21;
    }
}
```

输出结果
```
reflect.ReflectTest21
java.lang.IllegalAccessException: Class reflect.ReflectTest2 can not access a member of class reflect.ReflectTest21 with modifiers "private"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.Class.newInstance(Class.java:436)
	at reflect.ReflectTest2.main(ReflectTest2.java:14)
```

好像不行？看下下面这种方法

```java
package reflect;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;

public class ReflectTest2 {

    public static void main(String[] args) {
        try {
            Class<?> aClass = Class.forName("reflect.ReflectTest21");
            System.out.println(aClass.getName());

            Constructor<?> reflectTest21 = aClass.getDeclaredConstructor();
            reflectTest21.setAccessible(true);
            ReflectTest21 obj = (ReflectTest21) reflectTest21.newInstance();
            System.out.println(obj);

        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
    }
}

class ReflectTest21 {
    private static ReflectTest21 reflectTest21 = new ReflectTest21();
    private ReflectTest21() {}
    public static ReflectTest21 getInstance() {
        return reflectTest21;
    }
}
````

输出结果
```
reflect.ReflectTest21
reflect.ReflectTest21@1b6d3586
```

怎么样？反射很神奇又强大吧？有没有一种不太安全的感觉 ...

**Comment by peteryuanpan** [comment]
反射的性能测试，反射真的很慢吗？这类文章在网上层出不穷，其中有几篇写的比较好，进行了性能测试和原理分析

这边不妨也来进行下测试

```java
```
