### ISSUE TITLE
打破双亲委派之自定义类加载器

### ISSUE THREAD

**Issue by peteryuanpan** [peteryuanpan/notebook#82]
母ISSUE：https://github.com/peteryuanpan/notebook/issues/60
目标：实战一次课上所讲的自定义类加载器
对应课程部分：01:58:00前后

总结
- 继承ClassLoader类，重写loadClass方法
如果只是重写findClass方法，不算打破双亲委派
- 文章总结：[深入理解JAVA虚拟机-第一至四层/类加载器.md#自定义类加载器](https://github.com/peteryuanpan/notebook/blob/master/%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3JAVA%E8%99%9A%E6%8B%9F%E6%9C%BA-%E7%AC%AC%E4%B8%80%E8%87%B3%E5%9B%9B%E5%B1%82/%E7%B1%BB%E5%8A%A0%E8%BD%BD%E5%99%A8.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%B1%BB%E5%8A%A0%E8%BD%BD%E5%99%A8)

**Comment by peteryuanpan** [comment]
code5
```java
package com.luban.ziya.classloader;

public class Classloader_4 extends ClassLoader {

    public static void main(String[] args) throws Exception {
        Classloader_4 classloader1 = new Classloader_4();
        Class<?> clazz1 = classloader1.loadClass("com.luban.ziya.classloader.Classloader_4");
        System.out.println("clazz1: " + clazz1.getClassLoader());
        System.out.println("clazz1 hashcode: " + clazz1.hashCode());

        Classloader_4 classloader2 = new Classloader_4();
        Class<?> clazz2 = classloader2.loadClass("com.luban.ziya.classloader.Classloader_4");
        System.out.println("clazz2: " + clazz2.getClassLoader());
        System.out.println("clazz2 hashcode: " + clazz1.hashCode());

        System.out.println(clazz1 == clazz2);
    }

    @Override
    protected Class<?> findClass(String className) throws ClassNotFoundException {
        System.out.println("Classloader_4 findClass");
        return null;
    }

    @Override
    protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
        synchronized (getClassLoadingLock(name)) {
            // First, check if the class has already been loaded
            Class<?> c = findLoadedClass(name);
            if (c == null) {
                long t0 = System.nanoTime();

                if (name.startsWith("com.luban")) { // 打破双亲委派
                    c = findClass(name);
                } else {
                    c = this.getParent().loadClass(name);
                }

                if (c == null) {
                    // If still not found, then invoke findClass in order
                    // to find the class.
                    long t1 = System.nanoTime();
                    c = findClass(name);

                    // this is the defining class loader; record the stats
                    sun.misc.PerfCounter.getParentDelegationTime().addTime(t1 - t0);
                    sun.misc.PerfCounter.getFindClassTime().addElapsedTimeFrom(t1);
                    sun.misc.PerfCounter.getFindClasses().increment();
                }
            }
            if (resolve) {
                resolveClass(c);
            }
            return c;
        }
    }

}
```
code5输出结果
```
Classloader_4 findClass
Classloader_4 findClass
Exception in thread "main" java.lang.NullPointerException
	at com.luban.ziya.classloader.Classloader_4.main(Classloader_4.java:8)
```
- 解释：这个结果说明 if (name.startsWith("com.luban")) 这个语句段，打破了双亲委派

**Comment by peteryuanpan** [comment]
### 实现自定义加载类，指定路径加载.class文件
上面的例子太简单了，这边重新实现一个

目标：能够指定路径加载.class文件，生成一个class对象

首先，需要先实现一个Byte类，这里先将package定义为com.luban.ziya.peter

code2-1
```java
package com.luban.ziya.peter;

public class Byte {

    public static void main(String[] args) {
        Byte .show();
    }

    public static void show() {
        System.out.println("com.luban.ziya.peter.Byte show function");
    }

}
```

将这个类编译成Byte.class文件，预期应该是存储在target/classes/com/luban/ziya/peter/Byte.class中

现在将这份文件复制到D:\workspace\com\luban\ziya\peter下，然后删掉target/classes/com/luban/ziya/peter/Byte.class！

然后实现好下面的代码

code2-2
```java
package com.peter.jvm.example;

import java.io.File;
import java.net.URL;
import java.net.URLClassLoader;

public class URLClassLoaderTest2 {

    static String localpath = "D:\\workspace\\";
    static String classToLoad = "com.luban.ziya.peter.Byte";

    public static void main(String[] args) {
        try {
            File file = new File(localpath);
            URL url = file.toURI().toURL();
            ClassLoader myLoader = new URLClassLoader(new URL[]{url}) {
                protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
                    if (name == classToLoad) {
                        return super.findClass(name);
                    } else {
                        return getParent().loadClass(name);
                    }
                }
            };
            Class clazz = myLoader.loadClass(classToLoad);
            System.out.println(clazz.getName());
            clazz.getMethod("show").invoke((byte)1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

参考：https://stackoverflow.com/questions/6219829/method-to-dynamically-load-java-class-files

注意代码中的两个变量
    static String localpath = "D:\\workspace\\";
    static String classToLoad = "com.luban.ziya.peter.Byte";

启动main函数，得到如下结果
```
com.luban.ziya.peter.Byte
com.luban.ziya.peter.Byte show function
```

说明自定义类加载器加载了D:\workspace\com\luban\ziya\peter\Byte.class文件

还不够实锤？这边来debug下

来到URLClassLoader.java中，看到有以下方法

```java
    /**
     * Finds and loads the class with the specified name from the URL search
     * path. Any URLs referring to JAR files are loaded and opened as needed
     * until the class is found.
     *
     * @param name the name of the class
     * @return the resulting class
     * @exception ClassNotFoundException if the class could not be found,
     *            or if the loader is closed.
     * @exception NullPointerException if {@code name} is {@code null}.
     */
    protected Class<?> findClass(final String name)
        throws ClassNotFoundException
    {
        final Class<?> result;
        try {
            result = AccessController.doPrivileged(
                new PrivilegedExceptionAction<Class<?>>() {
                    public Class<?> run() throws ClassNotFoundException {
                        String path = name.replace('.', '/').concat(".class");
                        Resource res = ucp.getResource(path, false);
                        if (res != null) {
                            try {
                                return defineClass(name, res);
                            } catch (IOException e) {
                                throw new ClassNotFoundException(name, e);
                            }
                        } else {
                            return null;
                        }
                    }
                }, acc);
        } catch (java.security.PrivilegedActionException pae) {
            throw (ClassNotFoundException) pae.getException();
        }
        if (result == null) {
            throw new ClassNotFoundException(name);
        }
        return result;
    }
```

在 if (res != null) { 这一行加一个断点

再次启动main函数（debug模式），一路Resume，观察path的值，直到为com/luban/ziya/peter/Byte.class

这里有个res值，点开，发现url="file:/D:/workspace/com/luban/ziya/peter/Byte.class"

![image](https://user-images.githubusercontent.com/10209135/90924956-03fb2380-e423-11ea-9af5-86dc1421d7d5.png)

这下实锤了吧！

顺便提一下，上面代码中有 AccessController.doPrivileged ，这是**沙箱安全机制**，可以详见母ISSUE

**Comment by peteryuanpan** [comment]
### ClassLoader的Prohibited权限保护机制

上面我们实现了自定义加载一个.class文件，其中全限定名为com.luban.ziya.peter.Byte，这个全限定名在标准库中是不存在的

那么我们能否去加载一个标准库中存在的全限定名呢？比如java.lang.Byte！

还是按照上面的步骤，先实现一个Byte类，这里package是java.lang

code3-1
```java
package java.lang;

public class Byte {

    public static void main(String[] args) {
        Byte .show();
    }

    public static void show() {
        System.out.println("java.lang.Byte show function");
    }

}
```

将这个类编译成Byte.class文件，预期应该是存储在target/classes/java/lang/Byte.class中

现在将这份文件复制到D:\workspace\java\lang下，然后删掉target/classes/java/lang/Byte.class！

然后实现好下面的代码

code3-2
```java
package com.peter.jvm.example;

import java.io.File;
import java.net.URL;
import java.net.URLClassLoader;

public class URLClassLoaderTest2 {

    static String localpath = "D:\\workspace\\";
    static String classToLoad = "java.lang.Byte";

    public static void main(String[] args) {
        try {
            File file = new File(localpath);
            URL url = file.toURI().toURL();
            ClassLoader myLoader = new URLClassLoader(new URL[]{url}) {
                protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
                    if (name == classToLoad) {
                        return super.findClass(name);
                    } else {
                        return getParent().loadClass(name);
                    }
                }
            };
            Class clazz = myLoader.loadClass(classToLoad);
            System.out.println(clazz.getName());
            clazz.getMethod("show").invoke((byte)1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

其中code2-2与code3-2的区别，就是classToLoad的不同，从com.luban.ziya.peter.Byte变为了java.lang.Byte

执行main方法，得到如下报错
```
Exception in thread "main" java.lang.SecurityException: Prohibited package name: java.lang
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:655)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at com.luban.ziya.peter.ClassLoaderTest2.loadClass(ClassLoaderTest2.java:45)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.luban.ziya.peter.ClassLoaderTest2.main(ClassLoaderTest2.java:24)

Process finished with exit code 1
```

这是怎么回事？

查看at java.lang.ClassLoader.preDefineClass(ClassLoader.java:655)

```java
    /* Determine protection domain, and check that:
        - not define java.* class,
        - signer of this class matches signers for the rest of the classes in
          package.
    */
    private ProtectionDomain preDefineClass(String name,
                                            ProtectionDomain pd)
    {
        if (!checkName(name))
            throw new NoClassDefFoundError("IllegalName: " + name);

        // Note:  Checking logic in java.lang.invoke.MemberName.checkForTypeAlias
        // relies on the fact that spoofing is impossible if a class has a name
        // of the form "java.*"
        if ((name != null) && name.startsWith("java.")) {
            throw new SecurityException
                ("Prohibited package name: " +
                 name.substring(0, name.lastIndexOf('.')));
        }
        if (pd == null) {
            pd = defaultDomain;
        }

        if (name != null) checkCerts(name, pd.getCodeSource());

        return pd;
    }
```

可以发现ClassLoader采用了保护机制，对于java.开头的package，不允许preDefineClass（private修饰的），不允许从其他子类去defineClass（final修饰的），不允许重写方法，只允许通过ClassLoader类中的loadClass方法去加载，如下

```java
    protected Class<?> loadClass(String name, boolean resolve)
        throws ClassNotFoundException
    {
        synchronized (getClassLoadingLock(name)) {
            // First, check if the class has already been loaded
            Class<?> c = findLoadedClass(name);
            if (c == null) {
                long t0 = System.nanoTime();
                try {
                    if (parent != null) {
                        c = parent.loadClass(name, false);
                    } else {
                        c = findBootstrapClassOrNull(name);
                    }
                } catch (ClassNotFoundException e) {
                    // ClassNotFoundException thrown if class not found
                    // from the non-null parent class loader
                }
...
```

很明显，if (parent != null) { c = parent.loadClass(name, false);}  ，它只能通过父类加载器（启动类加载器）去加载，必须遵循双亲委派！

**Comment by peteryuanpan** [comment]
### defineClass的作用

看了下《深入理解JAVA虚拟机》第二版7.4.1节，觉得之前自己对ClassLoader的用法理解不够深入

之前以为只能通过ClassLoader类的loadClass方法去加载类字节流

实际上通过defineClass才是真正的从字节流去加载

这边来抄写一段代码
```java
package com.peter.jvm.example;

import java.io.InputStream;

public class ClassLoaderDefineClassTest1 {

    public static void main(String[] arg) throws Exception {
        ClassLoader myLoader = new ClassLoader() {
            @Override
            public Class<?> loadClass(String name) throws ClassNotFoundException {
                try {
                    String fileName = name.substring(name.lastIndexOf(".") + 1) + ".class";
                    InputStream is = getClass().getResourceAsStream(fileName);
                    System.out.println(name + (is == null ? " is null" : " is NOT null"));
                    if (is == null) {
                        return super.loadClass(name);
                    }
                    byte[] b = new byte[is.available()];
                    is.read(b);
                    return defineClass(name, b, 0, b.length);
                } catch (Exception e) {
                    throw new ClassNotFoundException(name);
                }
            }
        };
        Object obj = myLoader.loadClass("com.peter.jvm.example.ClassLoaderDefineClassTest1").newInstance();
        System.out.println(obj.getClass());
        System.out.println(obj instanceof com.peter.jvm.example.ClassLoaderDefineClassTest1);
    }
}
```

输出结果
```
com.peter.jvm.example.ClassLoaderDefineClassTest1 is NOT null
java.lang.Object is null
java.lang.ClassLoader is null
com.peter.jvm.example.ClassLoaderDefineClassTest1$1 is NOT null
class com.peter.jvm.example.ClassLoaderDefineClassTest1
false
```

来看一下defineClass的源码

```java
    protected final Class<?> defineClass(String name, byte[] b, int off, int len)
        throws ClassFormatError
    {
        return defineClass(name, b, off, len, null);
    }

    /**
     * Converts an array of bytes into an instance of class <tt>Class</tt>,
     * with an optional <tt>ProtectionDomain
     */
    protected final Class<?> defineClass(String name, byte[] b, int off, int len,
                                         ProtectionDomain protectionDomain)
        throws ClassFormatError
    {
        protectionDomain = preDefineClass(name, protectionDomain);
        String source = defineClassSourceLocation(protectionDomain);
        Class<?> c = defineClass1(name, b, off, len, protectionDomain, source);
        postDefineClass(c, protectionDomain);
        return c;
    }

    /**
     * Converts a {@link java.nio.ByteBuffer <tt>ByteBuffer</tt>}
     * into an instance of class <tt>Class
     */
    protected final Class<?> defineClass(String name, java.nio.ByteBuffer b,
                                         ProtectionDomain protectionDomain)
        throws ClassFormatError
    {
        int len = b.remaining();

        // Use byte[] if not a direct ByteBufer:
        if (!b.isDirect()) {
            if (b.hasArray()) {
                return defineClass(name, b.array(),
                                   b.position() + b.arrayOffset(), len,
                                   protectionDomain);
            } else {
                // no array, or read-only array
                byte[] tb = new byte[len];
                b.get(tb);  // get bytes out of byte buffer.
                return defineClass(name, tb, 0, len, protectionDomain);
            }
        }

        protectionDomain = preDefineClass(name, protectionDomain);
        String source = defineClassSourceLocation(protectionDomain);
        Class<?> c = defineClass2(name, b, b.position(), len, protectionDomain, source);
        postDefineClass(c, protectionDomain);
        return c;
    }

    private native Class<?> defineClass0(String name, byte[] b, int off, int len,
                                         ProtectionDomain pd);

    private native Class<?> defineClass1(String name, byte[] b, int off, int len,
                                         ProtectionDomain pd, String source);

    private native Class<?> defineClass2(String name, java.nio.ByteBuffer b,
                                         int off, int len, ProtectionDomain pd,
                                         String source);
```

**Comment by peteryuanpan** [comment]
### 自定义类加载打破双亲委派的关键
继承ClassLoader类，重写loadClass方法
如果只是重写findClass方法，不算打破双亲委派
